'use client';

import { useEffect, useMemo, useState } from 'react';
import {
  Brain,
  Sparkles,
  Copy,
  Share2,
  Loader2,
  History,
  Trash2,
  X,
  CheckCircle2,
  ArrowRight,
  Clock
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

const MODES = [
  { id: 'kid', label: 'Kid Mode', hint: 'Super simple' },
  { id: 'student', label: 'Student Mode', hint: 'Clear & educational' },
  { id: 'pro', label: 'Pro Mode', hint: 'Precise & nuanced' }
];

const STORAGE_KEY = 'brainmate.history.v1';

const copyText = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard');
  } catch (e) {
    toast.error('Could not copy');
  }
};

const formatForShare = (r) => {
  if (!r) return '';
  const steps = (r.step_by_step || []).map((s, i) => `${i + 1}. ${s}`).join('\n');
  const plan = (r.action_plan || [])
    .map((a, i) => `${i + 1}. ${a.step}${a.time ? ` — ${a.time}` : ''}`)
    .join('\n');
  return [
    `BrainMate — ${r.topic}`,
    '',
    `Simple Explanation:\n${r.simple_explanation}`,
    '',
    `Real-Life Analogy:\n${r.real_life_analogy}`,
    '',
    `Step-by-Step:\n${steps}`,
    '',
    `Summary:\n${r.summary}`,
    '',
    `Action Plan:\n${plan}`,
    '',
    '— Generated by BrainMate'
  ].join('\n');
};

function Card({ title, children, copyable, onCopy }) {
  return (
    <div className="fade-in-up rounded-2xl border border-[#E5E7EB] bg-white p-6 sm:p-7 soft-card-shadow">
      <div className="flex items-start justify-between gap-4 mb-3">
        <h3 className="text-[15px] font-semibold tracking-tight text-[#0B0B0F]">{title}</h3>
        {copyable && (
          <button
            onClick={onCopy}
            className="inline-flex items-center gap-1.5 text-xs text-[#6B7280] hover:text-[#0B0B0F] transition-colors"
            aria-label={`Copy ${title}`}
          >
            <Copy className="h-3.5 w-3.5" />
            Copy
          </button>
        )}
      </div>
      <div className="text-[15px] leading-relaxed text-[#0B0B0F]">{children}</div>
    </div>
  );
}

function ModePill({ active, children, hint, onClick }) {
  return (
    <button
      onClick={onClick}
      className={cn(
        'group relative px-4 py-2 rounded-xl text-sm font-medium transition-all border',
        active
          ? 'bg-[#0B0B0F] text-white border-[#0B0B0F] shadow-sm'
          : 'bg-white text-[#0B0B0F] border-[#E5E7EB] hover:border-[#0B0B0F]/30'
      )}
    >
      <span>{children}</span>
      <span
        className={cn(
          'ml-2 text-[11px]',
          active ? 'text-white/70' : 'text-[#6B7280]'
        )}
      >
        · {hint}
      </span>
    </button>
  );
}

function App() {
  const [topic, setTopic] = useState('');
  const [mode, setMode] = useState('student');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const [sidebarOpen, setSidebarOpen] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) setHistory(JSON.parse(raw));
    } catch (e) {}
  }, []);

  const persistHistory = (next) => {
    setHistory(next);
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
    } catch (e) {}
  };

  const handleExplain = async (overrideTopic, overrideMode) => {
    const t = (overrideTopic ?? topic).trim();
    const m = overrideMode ?? mode;
    if (!t) {
      toast.error('Type something to explain');
      return;
    }
    setLoading(true);
    setResult(null);
    try {
      const res = await fetch('/api/explain', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: t, mode: m })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || 'Something went wrong');

      setResult(data);
      const entry = {
        id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        topic: t,
        mode: m,
        created_at: new Date().toISOString(),
        payload: data
      };
      const next = [entry, ...history].slice(0, 50);
      persistHistory(next);
    } catch (err) {
      toast.error(err?.message || 'Failed to generate');
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    if (!result) return;
    const text = formatForShare(result);
    const shareData = {
      title: `BrainMate — ${result.topic}`,
      text,
      url: typeof window !== 'undefined' ? window.location.href : undefined
    };
    try {
      if (typeof navigator !== 'undefined' && navigator.share) {
        await navigator.share(shareData);
      } else {
        await navigator.clipboard.writeText(text);
        toast.success('Copied share text to clipboard');
      }
    } catch (e) {
      // ignore cancel
    }
  };

  const loadFromHistory = (entry) => {
    setTopic(entry.topic);
    setMode(entry.mode);
    setResult(entry.payload);
    setSidebarOpen(false);
    if (typeof window !== 'undefined') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const deleteFromHistory = (id) => {
    persistHistory(history.filter((h) => h.id !== id));
  };

  const clearHistory = () => {
    persistHistory([]);
  };

  const hasResult = !!result;

  return (
    <div className="min-h-screen bg-[#F8F9FB]">
      {/* Top bar */}
      <header className="sticky top-0 z-20 bg-[#F8F9FB]/80 backdrop-blur border-b border-[#E5E7EB]">
        <div className="mx-auto max-w-5xl px-5 sm:px-8 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="h-7 w-7 rounded-lg bg-[#0B0B0F] flex items-center justify-center">
              <Brain className="h-4 w-4 text-white" />
            </div>
            <span className="font-semibold tracking-tight text-[15px]">BrainMate</span>
          </div>
          <button
            onClick={() => setSidebarOpen(true)}
            className="inline-flex items-center gap-2 text-sm text-[#0B0B0F] hover:text-[#4F46E5] transition-colors"
          >
            <History className="h-4 w-4" />
            History {history.length > 0 && <span className="text-[#6B7280]">({history.length})</span>}
          </button>
        </div>
      </header>

      {/* Main */}
      <main className="mx-auto max-w-3xl px-5 sm:px-8 pt-14 sm:pt-20 pb-24">
        {/* Hero */}
        <div className="text-center mb-10 sm:mb-12 fade-in">
          <div className="inline-flex items-center gap-2 text-xs text-[#6B7280] bg-white border border-[#E5E7EB] rounded-full px-3 py-1 mb-6">
            <Sparkles className="h-3.5 w-3.5 text-[#4F46E5]" />
            AI-powered clarity
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-[#0B0B0F]">
            BrainMate
          </h1>
          <p className="mt-3 text-[#6B7280] text-base sm:text-lg">
            Understand anything. Take action.
          </p>
        </div>

        {/* Input card */}
        <div className="rounded-2xl border border-[#E5E7EB] bg-white p-4 sm:p-5 soft-card-shadow fade-in">
          <Textarea
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="What do you want to understand? e.g. How does a black hole work?"
            className="min-h-[96px] resize-none border-0 shadow-none focus-visible:ring-0 text-[16px] placeholder:text-[#9CA3AF] px-1"
            onKeyDown={(e) => {
              if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
                e.preventDefault();
                handleExplain();
              }
            }}
          />
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mt-3 pt-3 border-t border-[#F1F2F4]">
            <div className="flex flex-wrap items-center gap-2">
              {MODES.map((m) => (
                <ModePill
                  key={m.id}
                  active={mode === m.id}
                  hint={m.hint}
                  onClick={() => setMode(m.id)}
                >
                  {m.label}
                </ModePill>
              ))}
            </div>
            <Button
              onClick={() => handleExplain()}
              disabled={loading || !topic.trim()}
              className="bg-[#4F46E5] hover:bg-[#4338CA] text-white rounded-xl h-10 px-5 font-medium shadow-sm"
            >
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Thinking...
                </>
              ) : (
                <>
                  Explain
                  <ArrowRight className="h-4 w-4 ml-2" />
                </>
              )}
            </Button>
          </div>
          <div className="mt-2 text-[11px] text-[#9CA3AF] px-1">
            Tip: press ⌘/Ctrl + Enter to explain
          </div>
        </div>

        {/* Loading skeleton */}
        {loading && (
          <div className="mt-8 space-y-4 fade-in">
            {[0, 1, 2].map((i) => (
              <div
                key={i}
                className="h-24 rounded-2xl border border-[#E5E7EB] bg-white p-6 soft-card-shadow animate-pulse"
              >
                <div className="h-3 w-32 bg-[#F1F2F4] rounded mb-3" />
                <div className="h-3 w-full bg-[#F1F2F4] rounded mb-2" />
                <div className="h-3 w-4/5 bg-[#F1F2F4] rounded" />
              </div>
            ))}
          </div>
        )}

        {/* Results */}
        {hasResult && !loading && (
          <div className="mt-8 space-y-4">
            {/* Actions bar */}
            <div className="flex items-center justify-between fade-in">
              <div className="text-sm text-[#6B7280]">
                <span className="text-[#0B0B0F] font-medium">{result.topic}</span> · {result.mode} mode
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => copyText(formatForShare(result))}
                  className="inline-flex items-center gap-1.5 text-xs text-[#0B0B0F] bg-white border border-[#E5E7EB] rounded-lg px-3 py-1.5 hover:border-[#0B0B0F]/30 transition-colors"
                >
                  <Copy className="h-3.5 w-3.5" /> Copy all
                </button>
                <button
                  onClick={handleShare}
                  className="inline-flex items-center gap-1.5 text-xs text-[#0B0B0F] bg-white border border-[#E5E7EB] rounded-lg px-3 py-1.5 hover:border-[#0B0B0F]/30 transition-colors"
                >
                  <Share2 className="h-3.5 w-3.5" /> Share
                </button>
              </div>
            </div>

            <Card
              title="Simple Explanation"
              copyable
              onCopy={() => copyText(result.simple_explanation)}
            >
              <p>{result.simple_explanation}</p>
            </Card>

            <Card
              title="Real-Life Analogy"
              copyable
              onCopy={() => copyText(result.real_life_analogy)}
            >
              <p>{result.real_life_analogy}</p>
            </Card>

            <Card
              title="Step-by-Step Breakdown"
              copyable
              onCopy={() =>
                copyText((result.step_by_step || []).map((s, i) => `${i + 1}. ${s}`).join('\n'))
              }
            >
              <ul className="space-y-2.5">
                {(result.step_by_step || []).map((s, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="mt-0.5 text-[12px] font-semibold text-[#4F46E5] min-w-[20px]">
                      {String(i + 1).padStart(2, '0')}
                    </span>
                    <span>{s}</span>
                  </li>
                ))}
              </ul>
            </Card>

            <Card title="Quick Summary" copyable onCopy={() => copyText(result.summary)}>
              <p>{result.summary}</p>
            </Card>

            <Card
              title="What should you do next?"
              copyable
              onCopy={() =>
                copyText(
                  (result.action_plan || [])
                    .map((a, i) => `${i + 1}. ${a.step}${a.time ? ` — ${a.time}` : ''}`)
                    .join('\n')
                )
              }
            >
              <ul className="space-y-3">
                {(result.action_plan || []).map((a, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-3 pb-3 last:pb-0 border-b last:border-b-0 border-[#F1F2F4]"
                  >
                    <CheckCircle2 className="h-4 w-4 mt-0.5 text-[#4F46E5] shrink-0" />
                    <div className="flex-1">
                      <div className="text-[15px] text-[#0B0B0F]">{a.step}</div>
                      {a.time && (
                        <div className="mt-1 inline-flex items-center gap-1 text-[12px] text-[#6B7280]">
                          <Clock className="h-3 w-3" />
                          {a.time}
                        </div>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            </Card>
          </div>
        )}

        {/* Empty state suggestions */}
        {!hasResult && !loading && (
          <div className="mt-10 fade-in">
            <div className="text-xs uppercase tracking-wider text-[#9CA3AF] mb-3 text-center">
              Try one of these
            </div>
            <div className="flex flex-wrap justify-center gap-2">
              {[
                'How does compound interest work?',
                'Explain quantum entanglement',
                'What is a transformer model?',
                'How to build a habit that sticks',
                'Why do we dream?'
              ].map((s) => (
                <button
                  key={s}
                  onClick={() => {
                    setTopic(s);
                    handleExplain(s, mode);
                  }}
                  className="text-sm px-3 py-1.5 rounded-full bg-white border border-[#E5E7EB] text-[#0B0B0F] hover:border-[#0B0B0F]/30 transition-colors"
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
        )}
      </main>

      {/* History sidebar */}
      {sidebarOpen && (
        <div className="fixed inset-0 z-30">
          <div
            className="absolute inset-0 bg-black/20"
            onClick={() => setSidebarOpen(false)}
          />
          <aside className="absolute right-0 top-0 h-full w-full sm:w-[380px] bg-white border-l border-[#E5E7EB] shadow-xl flex flex-col">
            <div className="flex items-center justify-between px-5 h-14 border-b border-[#E5E7EB]">
              <div className="flex items-center gap-2">
                <History className="h-4 w-4" />
                <span className="font-semibold text-[15px]">History</span>
                <span className="text-xs text-[#6B7280]">({history.length})</span>
              </div>
              <div className="flex items-center gap-2">
                {history.length > 0 && (
                  <button
                    onClick={clearHistory}
                    className="text-xs text-[#6B7280] hover:text-[#0B0B0F]"
                  >
                    Clear all
                  </button>
                )}
                <button
                  onClick={() => setSidebarOpen(false)}
                  className="h-8 w-8 inline-flex items-center justify-center rounded-lg hover:bg-[#F1F2F4]"
                  aria-label="Close"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-y-auto p-3">
              {history.length === 0 ? (
                <div className="text-center text-sm text-[#6B7280] py-20">
                  No history yet.
                  <br />
                  Your past explanations will appear here.
                </div>
              ) : (
                <ul className="space-y-2">
                  {history.map((h) => (
                    <li
                      key={h.id}
                      className="group rounded-xl border border-[#E5E7EB] hover:border-[#0B0B0F]/30 bg-white transition-colors"
                    >
                      <div className="flex items-start gap-2 p-3">
                        <button
                          onClick={() => loadFromHistory(h)}
                          className="flex-1 text-left"
                        >
                          <div className="text-[14px] font-medium text-[#0B0B0F] line-clamp-2">
                            {h.topic}
                          </div>
                          <div className="mt-1 text-[11px] text-[#6B7280]">
                            {new Date(h.created_at).toLocaleString()} · {h.mode} mode
                          </div>
                        </button>
                        <button
                          onClick={() => deleteFromHistory(h.id)}
                          className="h-7 w-7 inline-flex items-center justify-center rounded-md text-[#9CA3AF] hover:text-[#0B0B0F] hover:bg-[#F1F2F4] opacity-0 group-hover:opacity-100 transition-opacity"
                          aria-label="Delete"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </aside>
        </div>
      )}

      {/* Footer */}
      <footer className="border-t border-[#E5E7EB] bg-white">
        <div className="mx-auto max-w-5xl px-5 sm:px-8 h-14 flex items-center justify-between text-xs text-[#6B7280]">
          <span>BrainMate · Understand anything. Take action.</span>
          <span>Powered by AI</span>
        </div>
      </footer>
    </div>
  );
}

export default App;
