'use client';

import { useEffect, useRef, useState } from 'react';
import {
  Brain,
  Sparkles,
  Copy,
  Share2,
  Loader2,
  History,
  Trash2,
  X,
  CheckCircle2,
  ArrowRight,
  Clock,
  Zap,
  MessageSquare,
  Send,
  Volume2,
  VolumeX,
  Pause,
  Play
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

const MODES = [
  { id: 'kid', label: 'Kid Mode', hint: 'Super simple' },
  { id: 'student', label: 'Student Mode', hint: 'Clear & educational' },
  { id: 'pro', label: 'Pro Mode', hint: 'Precise & nuanced' }
];

const STORAGE_KEY = 'brainmate.history.v1';

const copyText = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard');
  } catch (e) {
    toast.error('Could not copy');
  }
};

const formatForShare = (r) => {
  if (!r) return '';
  const steps = (r.step_by_step || []).map((s, i) => `${i + 1}. ${s}`).join('\n');
  const plan = (r.action_plan || [])
    .map((a, i) => `${i + 1}. ${a.step}${a.time ? ` — ${a.time}` : ''}`)
    .join('\n');
  return [
    `BrainMate — ${r.topic}`,
    '',
    `Simple Explanation:\n${r.simple_explanation}`,
    '',
    `Real-Life Analogy:\n${r.real_life_analogy}`,
    '',
    `Step-by-Step:\n${steps}`,
    '',
    `Summary:\n${r.summary}`,
    '',
    `Action Plan:\n${plan}`,
    '',
    '— Generated by BrainMate'
  ].join('\n');
};

// Parse the section-tagged running buffer into a partial result.
// Handles incomplete sections gracefully (used while streaming).
function parsePartial(buffer) {
  const out = {
    simple_explanation: '',
    real_life_analogy: '',
    step_by_step: [],
    summary: '',
    action_plan: [],
    active: null // which section is currently streaming
  };

  const sections = [
    { tag: 'SIMPLE', key: 'simple_explanation', type: 'text' },
    { tag: 'ANALOGY', key: 'real_life_analogy', type: 'text' },
    { tag: 'STEPS', key: 'step_by_step', type: 'bullets' },
    { tag: 'SUMMARY', key: 'summary', type: 'text' },
    { tag: 'ACTIONS', key: 'action_plan', type: 'actions' }
  ];

  for (const s of sections) {
    const openTag = `<<${s.tag}>>`;
    const startIdx = buffer.indexOf(openTag);
    if (startIdx === -1) continue;
    const afterStart = startIdx + openTag.length;
    const endIdx = buffer.indexOf('<<END>>', afterStart);
    const isClosed = endIdx !== -1;
    const raw = isClosed ? buffer.slice(afterStart, endIdx) : buffer.slice(afterStart);
    const content = raw.replace(/^\n+/, '').replace(/\n+$/, '');

    if (!isClosed) out.active = s.key;

    if (s.type === 'text') {
      out[s.key] = content;
    } else if (s.type === 'bullets') {
      out[s.key] = content
        .split('\n')
        .map((l) => l.replace(/^\s*[-*]\s*/, '').trim())
        .filter(Boolean);
    } else if (s.type === 'actions') {
      out[s.key] = content
        .split('\n')
        .map((l) => l.replace(/^\s*[-*]\s*/, '').trim())
        .filter(Boolean)
        .map((line) => {
          const m = line.match(/^\[([^\]]+)\]\s*(.*)$/);
          if (m) return { time: m[1].trim(), step: m[2].trim() };
          return { time: '', step: line };
        });
    }
  }
  return out;
}

function Card({ title, children, copyable, onCopy, streaming, speakable, isSpeaking, onSpeak, onStopSpeak }) {
  return (
    <div className="fade-in-up rounded-2xl border border-[#E5E7EB] bg-white p-6 sm:p-7 soft-card-shadow">
      <div className="flex items-start justify-between gap-4 mb-3">
        <div className="flex items-center gap-2">
          <h3 className="text-[15px] font-semibold tracking-tight text-[#0B0B0F]">{title}</h3>
          {streaming && (
            <span className="inline-flex items-center gap-1 text-[11px] text-[#4F46E5] bg-[#EEF2FF] border border-[#E0E7FF] rounded-full px-2 py-0.5">
              <span className="h-1.5 w-1.5 rounded-full bg-[#4F46E5] animate-pulse" />
              writing
            </span>
          )}
        </div>
        <div className="flex items-center gap-3 shrink-0">
          {speakable && (
            <button
              onClick={isSpeaking ? onStopSpeak : onSpeak}
              className={cn(
                'inline-flex items-center gap-1.5 text-xs transition-colors',
                isSpeaking ? 'text-[#4F46E5]' : 'text-[#6B7280] hover:text-[#0B0B0F]'
              )}
              aria-label={isSpeaking ? `Stop speaking ${title}` : `Listen to ${title}`}
            >
              {isSpeaking ? <VolumeX className="h-3.5 w-3.5" /> : <Volume2 className="h-3.5 w-3.5" />}
              {isSpeaking ? 'Stop' : 'Listen'}
            </button>
          )}
          {copyable && (
            <button
              onClick={onCopy}
              className="inline-flex items-center gap-1.5 text-xs text-[#6B7280] hover:text-[#0B0B0F] transition-colors"
              aria-label={`Copy ${title}`}
            >
              <Copy className="h-3.5 w-3.5" />
              Copy
            </button>
          )}
        </div>
      </div>
      <div className="text-[15px] leading-relaxed text-[#0B0B0F]">{children}</div>
    </div>
  );
}

function ModePill({ active, children, hint, onClick }) {
  return (
    <button
      onClick={onClick}
      className={cn(
        'group relative px-4 py-2 rounded-xl text-sm font-medium transition-all border',
        active
          ? 'bg-[#0B0B0F] text-white border-[#0B0B0F] shadow-sm'
          : 'bg-white text-[#0B0B0F] border-[#E5E7EB] hover:border-[#0B0B0F]/30'
      )}
    >
      <span>{children}</span>
      <span
        className={cn('ml-2 text-[11px]', active ? 'text-white/70' : 'text-[#6B7280]')}
      >
        · {hint}
      </span>
    </button>
  );
}

function App() {
  const [topic, setTopic] = useState('');
  const [mode, setMode] = useState('student');
  const [loading, setLoading] = useState(false);
  const [streaming, setStreaming] = useState(false);
  const [result, setResult] = useState(null);
  const [activeSection, setActiveSection] = useState(null);
  const [history, setHistory] = useState([]);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const abortRef = useRef(null);

  // Chat state
  const [chatMessages, setChatMessages] = useState([]); // [{role:'user'|'assistant', content:''}]
  const [chatInput, setChatInput] = useState('');
  const [chatStreaming, setChatStreaming] = useState(false);
  const chatAbortRef = useRef(null);
  const chatEndRef = useRef(null);

  // Voice state
  const [speaking, setSpeaking] = useState(false);
  const [speakingWhat, setSpeakingWhat] = useState(null); // e.g. 'all' | 'summary' | key
  const [voiceSupported, setVoiceSupported] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) setHistory(JSON.parse(raw));
    } catch (e) {}
  }, []);

  // Voice capability
  useEffect(() => {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      setVoiceSupported(true);
    }
    return () => {
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  // Auto-scroll chat
  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: 'smooth', block: 'end' });
    }
  }, [chatMessages, chatStreaming]);

  // Voice helpers
  const stopSpeaking = () => {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    setSpeaking(false);
    setSpeakingWhat(null);
  };

  const speak = (text, tag = 'section') => {
    if (!voiceSupported || !text) return;
    // Cancel any ongoing
    window.speechSynthesis.cancel();
    // Split long text into chunks for reliability (some browsers cut off >200 chars)
    const chunks = String(text).match(/[^.!?]+[.!?]+|[^.!?]+$/g) || [String(text)];
    setSpeaking(true);
    setSpeakingWhat(tag);
    let idx = 0;
    const playNext = () => {
      if (idx >= chunks.length) {
        setSpeaking(false);
        setSpeakingWhat(null);
        return;
      }
      const u = new SpeechSynthesisUtterance(chunks[idx].trim());
      u.rate = 1.0;
      u.pitch = 1.0;
      u.volume = 1.0;
      u.onend = () => {
        idx += 1;
        playNext();
      };
      u.onerror = () => {
        setSpeaking(false);
        setSpeakingWhat(null);
      };
      window.speechSynthesis.speak(u);
    };
    playNext();
  };

  const speakAll = (r) => {
    if (!r) return;
    const parts = [
      r.simple_explanation,
      r.real_life_analogy,
      ...(r.step_by_step || []),
      r.summary
    ].filter(Boolean);
    speak(parts.join('. '), 'all');
  };

  const persistHistory = (next) => {
    setHistory(next);
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
    } catch (e) {}
  };

  const saveToHistory = (entry) => {
    setHistory((prev) => {
      const next = [entry, ...prev].slice(0, 50);
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
      } catch (e) {}
      return next;
    });
  };

  const handleExplain = async (overrideTopic, overrideMode) => {
    const t = (overrideTopic ?? topic).trim();
    const m = overrideMode ?? mode;
    if (!t) {
      toast.error('Type something to explain');
      return;
    }

    // Cancel any in-flight stream
    if (abortRef.current) {
      try {
        abortRef.current.abort();
      } catch (e) {}
    }
    // Stop any speaking and reset chat for the new topic
    stopSpeaking();
    setChatMessages([]);
    if (chatAbortRef.current) {
      try {
        chatAbortRef.current.abort();
      } catch (e) {}
      chatAbortRef.current = null;
    }
    setChatStreaming(false);

    const ctrl = new AbortController();
    abortRef.current = ctrl;

    setLoading(true);
    setStreaming(true);
    setResult({
      topic: t,
      mode: m,
      simple_explanation: '',
      real_life_analogy: '',
      step_by_step: [],
      summary: '',
      action_plan: []
    });
    setActiveSection('simple_explanation');

    let buffer = '';
    let rafPending = false;
    const flushUpdate = () => {
      rafPending = false;
      const partial = parsePartial(buffer);
      setResult((prev) => ({
        ...(prev || {}),
        topic: t,
        mode: m,
        simple_explanation: partial.simple_explanation,
        real_life_analogy: partial.real_life_analogy,
        step_by_step: partial.step_by_step,
        summary: partial.summary,
        action_plan: partial.action_plan
      }));
      setActiveSection(partial.active);
    };
    const scheduleFlush = () => {
      if (rafPending) return;
      rafPending = true;
      if (typeof requestAnimationFrame !== 'undefined') {
        requestAnimationFrame(flushUpdate);
      } else {
        setTimeout(flushUpdate, 16);
      }
    };

    try {
      const res = await fetch('/api/explain/stream', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: t, mode: m }),
        signal: ctrl.signal
      });

      if (!res.ok || !res.body) {
        const errBody = await res.json().catch(() => ({}));
        throw new Error(errBody?.error || `Request failed (${res.status})`);
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let sseBuf = '';

      // Read SSE stream: events separated by blank line
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        sseBuf += decoder.decode(value, { stream: true });

        let sepIdx;
        while ((sepIdx = sseBuf.indexOf('\n\n')) !== -1) {
          const chunk = sseBuf.slice(0, sepIdx);
          sseBuf = sseBuf.slice(sepIdx + 2);

          let evt = 'message';
          let dataLine = '';
          for (const line of chunk.split('\n')) {
            if (line.startsWith('event:')) evt = line.slice(6).trim();
            else if (line.startsWith('data:')) dataLine += line.slice(5).trim();
          }
          if (!dataLine) continue;

          if (evt === 'token') {
            try {
              const { text } = JSON.parse(dataLine);
              if (typeof text === 'string') {
                buffer += text;
                scheduleFlush();
              }
            } catch (e) {}
          } else if (evt === 'done') {
            // Final parse
            flushUpdate();
          } else if (evt === 'error') {
            try {
              const { message } = JSON.parse(dataLine);
              throw new Error(message || 'Stream error');
            } catch (e) {
              throw e;
            }
          }
        }
      }
      // Final flush and save
      flushUpdate();
      const finalPartial = parsePartial(buffer);
      const finalResult = {
        topic: t,
        mode: m,
        generated_at: new Date().toISOString(),
        simple_explanation: finalPartial.simple_explanation,
        real_life_analogy: finalPartial.real_life_analogy,
        step_by_step: finalPartial.step_by_step,
        summary: finalPartial.summary,
        action_plan: finalPartial.action_plan
      };
      setResult(finalResult);
      setActiveSection(null);

      if (
        finalResult.simple_explanation ||
        finalResult.summary ||
        finalResult.step_by_step.length
      ) {
        saveToHistory({
          id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          topic: t,
          mode: m,
          created_at: new Date().toISOString(),
          payload: finalResult
        });
      }
    } catch (err) {
      if (err?.name === 'AbortError') {
        // ignore — user cancelled
      } else {
        toast.error(err?.message || 'Failed to generate');
      }
    } finally {
      setLoading(false);
      setStreaming(false);
      abortRef.current = null;
    }
  };

  const handleStop = () => {
    if (abortRef.current) {
      abortRef.current.abort();
      abortRef.current = null;
    }
    setStreaming(false);
    setLoading(false);
  };

  // -------- Follow-up chat --------
  const sendChatMessage = async () => {
    const text = chatInput.trim();
    if (!text || chatStreaming || !result) return;

    // Cancel any in-flight
    if (chatAbortRef.current) {
      try {
        chatAbortRef.current.abort();
      } catch (e) {}
    }
    const ctrl = new AbortController();
    chatAbortRef.current = ctrl;

    const userMsg = { role: 'user', content: text };
    const assistantMsg = { role: 'assistant', content: '' };
    const nextMsgs = [...chatMessages, userMsg, assistantMsg];
    setChatMessages(nextMsgs);
    setChatInput('');
    setChatStreaming(true);

    // Build context from current explanation
    const ctx = [
      result.simple_explanation ? `Simple explanation: ${result.simple_explanation}` : '',
      result.real_life_analogy ? `Analogy: ${result.real_life_analogy}` : '',
      result.step_by_step?.length ? `Steps: ${result.step_by_step.join(' | ')}` : '',
      result.summary ? `Summary: ${result.summary}` : ''
    ]
      .filter(Boolean)
      .join('\n');

    // Messages to send: everything except the empty assistant placeholder
    const sendMessages = nextMsgs
      .slice(0, -1)
      .map((m) => ({ role: m.role, content: m.content }));

    try {
      const res = await fetch('/api/chat/stream', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: result.topic,
          mode: result.mode,
          context: ctx,
          messages: sendMessages
        }),
        signal: ctrl.signal
      });
      if (!res.ok || !res.body) {
        const errBody = await res.json().catch(() => ({}));
        throw new Error(errBody?.error || `Request failed (${res.status})`);
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let sseBuf = '';
      let assistantText = '';

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        sseBuf += decoder.decode(value, { stream: true });
        let sepIdx;
        while ((sepIdx = sseBuf.indexOf('\n\n')) !== -1) {
          const chunk = sseBuf.slice(0, sepIdx);
          sseBuf = sseBuf.slice(sepIdx + 2);
          let evt = 'message';
          let dataLine = '';
          for (const line of chunk.split('\n')) {
            if (line.startsWith('event:')) evt = line.slice(6).trim();
            else if (line.startsWith('data:')) dataLine += line.slice(5).trim();
          }
          if (!dataLine) continue;
          if (evt === 'token') {
            try {
              const { text: t } = JSON.parse(dataLine);
              if (typeof t === 'string') {
                assistantText += t;
                setChatMessages((prev) => {
                  const copy = prev.slice();
                  const last = copy[copy.length - 1];
                  if (last && last.role === 'assistant') {
                    copy[copy.length - 1] = { ...last, content: assistantText };
                  }
                  return copy;
                });
              }
            } catch (e) {}
          } else if (evt === 'error') {
            try {
              const { message } = JSON.parse(dataLine);
              throw new Error(message || 'Chat error');
            } catch (e) {
              throw e;
            }
          }
        }
      }
    } catch (err) {
      if (err?.name !== 'AbortError') {
        toast.error(err?.message || 'Chat failed');
        // Replace empty assistant bubble with error marker
        setChatMessages((prev) => {
          const copy = prev.slice();
          const last = copy[copy.length - 1];
          if (last && last.role === 'assistant' && !last.content) {
            copy[copy.length - 1] = {
              ...last,
              content: '⚠️ Could not generate a reply. Try again.'
            };
          }
          return copy;
        });
      }
    } finally {
      setChatStreaming(false);
      chatAbortRef.current = null;
    }
  };

  const handleShare = async () => {
    if (!result) return;
    const text = formatForShare(result);
    const shareData = {
      title: `BrainMate — ${result.topic}`,
      text,
      url: typeof window !== 'undefined' ? window.location.href : undefined
    };
    try {
      if (typeof navigator !== 'undefined' && navigator.share) {
        await navigator.share(shareData);
      } else {
        await navigator.clipboard.writeText(text);
        toast.success('Copied share text to clipboard');
      }
    } catch (e) {
      // ignore cancel
    }
  };

  const loadFromHistory = (entry) => {
    stopSpeaking();
    setChatMessages([]);
    setTopic(entry.topic);
    setMode(entry.mode);
    setResult(entry.payload);
    setActiveSection(null);
    setSidebarOpen(false);
    if (typeof window !== 'undefined') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const deleteFromHistory = (id) => {
    persistHistory(history.filter((h) => h.id !== id));
  };

  const clearHistory = () => {
    persistHistory([]);
  };

  const hasAnyContent =
    !!result &&
    (result.simple_explanation ||
      result.real_life_analogy ||
      (result.step_by_step && result.step_by_step.length) ||
      result.summary ||
      (result.action_plan && result.action_plan.length));

  return (
    <div className="min-h-screen bg-[#F8F9FB]">
      {/* Top bar */}
      <header className="sticky top-0 z-20 bg-[#F8F9FB]/80 backdrop-blur border-b border-[#E5E7EB]">
        <div className="mx-auto max-w-5xl px-5 sm:px-8 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="h-7 w-7 rounded-lg bg-[#0B0B0F] flex items-center justify-center">
              <Brain className="h-4 w-4 text-white" />
            </div>
            <span className="font-semibold tracking-tight text-[15px]">BrainMate</span>
          </div>
          <button
            onClick={() => setSidebarOpen(true)}
            className="inline-flex items-center gap-2 text-sm text-[#0B0B0F] hover:text-[#4F46E5] transition-colors"
          >
            <History className="h-4 w-4" />
            History {history.length > 0 && <span className="text-[#6B7280]">({history.length})</span>}
          </button>
        </div>
      </header>

      {/* Main */}
      <main className="mx-auto max-w-3xl px-5 sm:px-8 pt-14 sm:pt-20 pb-24">
        {/* Hero */}
        <div className="text-center mb-10 sm:mb-12 fade-in">
          <div className="inline-flex items-center gap-2 text-xs text-[#6B7280] bg-white border border-[#E5E7EB] rounded-full px-3 py-1 mb-6">
            <Sparkles className="h-3.5 w-3.5 text-[#4F46E5]" />
            AI-powered clarity · streaming live
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-[#0B0B0F]">
            BrainMate
          </h1>
          <p className="mt-3 text-[#6B7280] text-base sm:text-lg">
            Understand anything. Take action.
          </p>
        </div>

        {/* Input card */}
        <div className="rounded-2xl border border-[#E5E7EB] bg-white p-4 sm:p-5 soft-card-shadow fade-in">
          <Textarea
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="What do you want to understand? e.g. How does a black hole work?"
            className="min-h-[96px] resize-none border-0 shadow-none focus-visible:ring-0 text-[16px] placeholder:text-[#9CA3AF] px-1"
            onKeyDown={(e) => {
              if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
                e.preventDefault();
                handleExplain();
              }
            }}
          />
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mt-3 pt-3 border-t border-[#F1F2F4]">
            <div className="flex flex-wrap items-center gap-2">
              {MODES.map((m) => (
                <ModePill
                  key={m.id}
                  active={mode === m.id}
                  hint={m.hint}
                  onClick={() => setMode(m.id)}
                >
                  {m.label}
                </ModePill>
              ))}
            </div>
            {streaming ? (
              <Button
                onClick={handleStop}
                variant="outline"
                className="rounded-xl h-10 px-5 font-medium border-[#E5E7EB]"
              >
                <X className="h-4 w-4 mr-2" />
                Stop
              </Button>
            ) : (
              <Button
                onClick={() => handleExplain()}
                disabled={loading || !topic.trim()}
                className="bg-[#4F46E5] hover:bg-[#4338CA] text-white rounded-xl h-10 px-5 font-medium shadow-sm"
              >
                {loading ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Thinking...
                  </>
                ) : (
                  <>
                    Explain
                    <ArrowRight className="h-4 w-4 ml-2" />
                  </>
                )}
              </Button>
            )}
          </div>
          <div className="mt-2 text-[11px] text-[#9CA3AF] px-1 flex items-center gap-1.5">
            <Zap className="h-3 w-3" />
            Tip: press ⌘/Ctrl + Enter to explain · streams in real time
          </div>
        </div>

        {/* Results */}
        {(streaming || hasAnyContent) && (
          <div className="mt-8 space-y-4">
            {/* Actions bar */}
            {result && (
              <div className="flex items-center justify-between fade-in">
                <div className="text-sm text-[#6B7280] truncate">
                  <span className="text-[#0B0B0F] font-medium">{result.topic}</span> · {result.mode} mode
                </div>
                {hasAnyContent && !streaming && (
                  <div className="flex items-center gap-2 shrink-0 ml-3">
                    {voiceSupported && (
                      <button
                        onClick={() => (speaking && speakingWhat === 'all' ? stopSpeaking() : speakAll(result))}
                        className={cn(
                          'inline-flex items-center gap-1.5 text-xs bg-white border rounded-lg px-3 py-1.5 transition-colors',
                          speaking && speakingWhat === 'all'
                            ? 'text-[#4F46E5] border-[#C7D2FE] bg-[#EEF2FF]'
                            : 'text-[#0B0B0F] border-[#E5E7EB] hover:border-[#0B0B0F]/30'
                        )}
                        aria-label={speaking && speakingWhat === 'all' ? 'Stop speaking' : 'Listen to all'}
                      >
                        {speaking && speakingWhat === 'all' ? (
                          <>
                            <VolumeX className="h-3.5 w-3.5" /> Stop
                          </>
                        ) : (
                          <>
                            <Volume2 className="h-3.5 w-3.5" /> Listen
                          </>
                        )}
                      </button>
                    )}
                    <button
                      onClick={() => copyText(formatForShare(result))}
                      className="inline-flex items-center gap-1.5 text-xs text-[#0B0B0F] bg-white border border-[#E5E7EB] rounded-lg px-3 py-1.5 hover:border-[#0B0B0F]/30 transition-colors"
                    >
                      <Copy className="h-3.5 w-3.5" /> Copy all
                    </button>
                    <button
                      onClick={handleShare}
                      className="inline-flex items-center gap-1.5 text-xs text-[#0B0B0F] bg-white border border-[#E5E7EB] rounded-lg px-3 py-1.5 hover:border-[#0B0B0F]/30 transition-colors"
                    >
                      <Share2 className="h-3.5 w-3.5" /> Share
                    </button>
                  </div>
                )}
              </div>
            )}

            {(result?.simple_explanation || activeSection === 'simple_explanation') && (
              <Card
                title="Simple Explanation"
                copyable={!streaming}
                streaming={streaming && activeSection === 'simple_explanation'}
                onCopy={() => copyText(result.simple_explanation)}
                speakable={voiceSupported && !streaming && !!result?.simple_explanation}
                isSpeaking={speaking && speakingWhat === 'simple_explanation'}
                onSpeak={() => speak(result.simple_explanation, 'simple_explanation')}
                onStopSpeak={stopSpeaking}
              >
                <p className="whitespace-pre-wrap">
                  {result.simple_explanation || <span className="text-[#9CA3AF]">Writing…</span>}
                  {streaming && activeSection === 'simple_explanation' && (
                    <span className="inline-block w-[2px] h-4 bg-[#4F46E5] align-middle ml-0.5 animate-pulse" />
                  )}
                </p>
              </Card>
            )}

            {(result?.real_life_analogy || activeSection === 'real_life_analogy') && (
              <Card
                title="Real-Life Analogy"
                copyable={!streaming}
                streaming={streaming && activeSection === 'real_life_analogy'}
                onCopy={() => copyText(result.real_life_analogy)}
                speakable={voiceSupported && !streaming && !!result?.real_life_analogy}
                isSpeaking={speaking && speakingWhat === 'real_life_analogy'}
                onSpeak={() => speak(result.real_life_analogy, 'real_life_analogy')}
                onStopSpeak={stopSpeaking}
              >
                <p className="whitespace-pre-wrap">
                  {result.real_life_analogy || <span className="text-[#9CA3AF]">Writing…</span>}
                  {streaming && activeSection === 'real_life_analogy' && (
                    <span className="inline-block w-[2px] h-4 bg-[#4F46E5] align-middle ml-0.5 animate-pulse" />
                  )}
                </p>
              </Card>
            )}

            {((result?.step_by_step && result.step_by_step.length > 0) || activeSection === 'step_by_step') && (
              <Card
                title="Step-by-Step Breakdown"
                copyable={!streaming}
                streaming={streaming && activeSection === 'step_by_step'}
                onCopy={() =>
                  copyText((result.step_by_step || []).map((s, i) => `${i + 1}. ${s}`).join('\n'))
                }
              >
                <ul className="space-y-2.5">
                  {(result?.step_by_step || []).map((s, i) => (
                    <li key={i} className="flex gap-3 fade-in">
                      <span className="mt-0.5 text-[12px] font-semibold text-[#4F46E5] min-w-[20px]">
                        {String(i + 1).padStart(2, '0')}
                      </span>
                      <span>{s}</span>
                    </li>
                  ))}
                  {streaming && activeSection === 'step_by_step' && (!result?.step_by_step || result.step_by_step.length === 0) && (
                    <li className="text-[#9CA3AF]">Writing…</li>
                  )}
                </ul>
              </Card>
            )}

            {(result?.summary || activeSection === 'summary') && (
              <Card
                title="Quick Summary"
                copyable={!streaming}
                streaming={streaming && activeSection === 'summary'}
                onCopy={() => copyText(result.summary)}
                speakable={voiceSupported && !streaming && !!result?.summary}
                isSpeaking={speaking && speakingWhat === 'summary'}
                onSpeak={() => speak(result.summary, 'summary')}
                onStopSpeak={stopSpeaking}
              >
                <p className="whitespace-pre-wrap">
                  {result.summary || <span className="text-[#9CA3AF]">Writing…</span>}
                  {streaming && activeSection === 'summary' && (
                    <span className="inline-block w-[2px] h-4 bg-[#4F46E5] align-middle ml-0.5 animate-pulse" />
                  )}
                </p>
              </Card>
            )}

            {((result?.action_plan && result.action_plan.length > 0) || activeSection === 'action_plan') && (
              <Card
                title="What should you do next?"
                copyable={!streaming}
                streaming={streaming && activeSection === 'action_plan'}
                onCopy={() =>
                  copyText(
                    (result.action_plan || [])
                      .map((a, i) => `${i + 1}. ${a.step}${a.time ? ` — ${a.time}` : ''}`)
                      .join('\n')
                  )
                }
              >
                <ul className="space-y-3">
                  {(result?.action_plan || []).map((a, i) => (
                    <li
                      key={i}
                      className="flex items-start gap-3 pb-3 last:pb-0 border-b last:border-b-0 border-[#F1F2F4] fade-in"
                    >
                      <CheckCircle2 className="h-4 w-4 mt-0.5 text-[#4F46E5] shrink-0" />
                      <div className="flex-1">
                        <div className="text-[15px] text-[#0B0B0F]">{a.step}</div>
                        {a.time && (
                          <div className="mt-1 inline-flex items-center gap-1 text-[12px] text-[#6B7280]">
                            <Clock className="h-3 w-3" />
                            {a.time}
                          </div>
                        )}
                      </div>
                    </li>
                  ))}
                  {streaming && activeSection === 'action_plan' && (!result?.action_plan || result.action_plan.length === 0) && (
                    <li className="text-[#9CA3AF]">Writing…</li>
                  )}
                </ul>
              </Card>
            )}

            {/* Follow-up chat */}
            {hasAnyContent && !streaming && (
              <div className="mt-4 rounded-2xl border border-[#E5E7EB] bg-white soft-card-shadow fade-in-up overflow-hidden">
                <div className="flex items-center gap-2 px-6 pt-5 pb-3 border-b border-[#F1F2F4]">
                  <MessageSquare className="h-4 w-4 text-[#4F46E5]" />
                  <h3 className="text-[15px] font-semibold tracking-tight text-[#0B0B0F]">
                    Ask a follow-up
                  </h3>
                  <span className="text-xs text-[#6B7280]">
                    about "{result.topic}"
                  </span>
                </div>

                {chatMessages.length > 0 && (
                  <div className="px-6 py-4 space-y-4 max-h-[480px] overflow-y-auto">
                    {chatMessages.map((m, i) => (
                      <div
                        key={i}
                        className={cn(
                          'flex',
                          m.role === 'user' ? 'justify-end' : 'justify-start'
                        )}
                      >
                        <div
                          className={cn(
                            'max-w-[85%] rounded-2xl px-4 py-2.5 text-[14px] leading-relaxed whitespace-pre-wrap',
                            m.role === 'user'
                              ? 'bg-[#0B0B0F] text-white rounded-br-md'
                              : 'bg-[#F1F2F4] text-[#0B0B0F] rounded-bl-md'
                          )}
                        >
                          {m.content || (
                            <span className="inline-flex items-center gap-2 text-[#6B7280]">
                              <Loader2 className="h-3.5 w-3.5 animate-spin" />
                              Thinking…
                            </span>
                          )}
                          {m.role === 'assistant' &&
                            chatStreaming &&
                            i === chatMessages.length - 1 &&
                            m.content && (
                              <span className="inline-block w-[2px] h-4 bg-[#4F46E5] align-middle ml-0.5 animate-pulse" />
                            )}
                        </div>
                      </div>
                    ))}
                    <div ref={chatEndRef} />
                  </div>
                )}

                <div className="px-4 sm:px-5 py-3 border-t border-[#F1F2F4] bg-[#FAFAFB]">
                  <div className="flex items-end gap-2">
                    <Textarea
                      value={chatInput}
                      onChange={(e) => setChatInput(e.target.value)}
                      placeholder={
                        chatMessages.length === 0
                          ? 'Ask anything about this explanation…'
                          : 'Continue the conversation…'
                      }
                      className="min-h-[44px] max-h-[120px] resize-none bg-white border border-[#E5E7EB] rounded-xl text-[14px] focus-visible:ring-1 focus-visible:ring-[#4F46E5]"
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && !e.shiftKey) {
                          e.preventDefault();
                          sendChatMessage();
                        }
                      }}
                      disabled={chatStreaming}
                    />
                    <Button
                      onClick={sendChatMessage}
                      disabled={chatStreaming || !chatInput.trim()}
                      className="bg-[#4F46E5] hover:bg-[#4338CA] text-white rounded-xl h-[44px] w-[44px] p-0 shrink-0"
                      aria-label="Send"
                    >
                      {chatStreaming ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Send className="h-4 w-4" />
                      )}
                    </Button>
                  </div>
                  {chatMessages.length === 0 && (
                    <div className="mt-2 flex flex-wrap gap-1.5">
                      {[
                        'Give me a concrete example',
                        'Why does this matter?',
                        'What are common mistakes?',
                        'Explain it even simpler'
                      ].map((s) => (
                        <button
                          key={s}
                          onClick={() => setChatInput(s)}
                          className="text-[12px] px-2.5 py-1 rounded-full bg-white border border-[#E5E7EB] text-[#6B7280] hover:text-[#0B0B0F] hover:border-[#0B0B0F]/30 transition-colors"
                        >
                          {s}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Empty state suggestions */}
        {!streaming && !hasAnyContent && (
          <div className="mt-10 fade-in">
            <div className="text-xs uppercase tracking-wider text-[#9CA3AF] mb-3 text-center">
              Try one of these
            </div>
            <div className="flex flex-wrap justify-center gap-2">
              {[
                'How does compound interest work?',
                'Explain quantum entanglement',
                'What is a transformer model?',
                'How to build a habit that sticks',
                'Why do we dream?'
              ].map((s) => (
                <button
                  key={s}
                  onClick={() => {
                    setTopic(s);
                    handleExplain(s, mode);
                  }}
                  className="text-sm px-3 py-1.5 rounded-full bg-white border border-[#E5E7EB] text-[#0B0B0F] hover:border-[#0B0B0F]/30 transition-colors"
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
        )}
      </main>

      {/* History sidebar */}
      {sidebarOpen && (
        <div className="fixed inset-0 z-30">
          <div className="absolute inset-0 bg-black/20" onClick={() => setSidebarOpen(false)} />
          <aside className="absolute right-0 top-0 h-full w-full sm:w-[380px] bg-white border-l border-[#E5E7EB] shadow-xl flex flex-col">
            <div className="flex items-center justify-between px-5 h-14 border-b border-[#E5E7EB]">
              <div className="flex items-center gap-2">
                <History className="h-4 w-4" />
                <span className="font-semibold text-[15px]">History</span>
                <span className="text-xs text-[#6B7280]">({history.length})</span>
              </div>
              <div className="flex items-center gap-2">
                {history.length > 0 && (
                  <button
                    onClick={clearHistory}
                    className="text-xs text-[#6B7280] hover:text-[#0B0B0F]"
                  >
                    Clear all
                  </button>
                )}
                <button
                  onClick={() => setSidebarOpen(false)}
                  className="h-8 w-8 inline-flex items-center justify-center rounded-lg hover:bg-[#F1F2F4]"
                  aria-label="Close"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-y-auto p-3">
              {history.length === 0 ? (
                <div className="text-center text-sm text-[#6B7280] py-20">
                  No history yet.
                  <br />
                  Your past explanations will appear here.
                </div>
              ) : (
                <ul className="space-y-2">
                  {history.map((h) => (
                    <li
                      key={h.id}
                      className="group rounded-xl border border-[#E5E7EB] hover:border-[#0B0B0F]/30 bg-white transition-colors"
                    >
                      <div className="flex items-start gap-2 p-3">
                        <button onClick={() => loadFromHistory(h)} className="flex-1 text-left">
                          <div className="text-[14px] font-medium text-[#0B0B0F] line-clamp-2">
                            {h.topic}
                          </div>
                          <div className="mt-1 text-[11px] text-[#6B7280]">
                            {new Date(h.created_at).toLocaleString()} · {h.mode} mode
                          </div>
                        </button>
                        <button
                          onClick={() => deleteFromHistory(h.id)}
                          className="h-7 w-7 inline-flex items-center justify-center rounded-md text-[#9CA3AF] hover:text-[#0B0B0F] hover:bg-[#F1F2F4] opacity-0 group-hover:opacity-100 transition-opacity"
                          aria-label="Delete"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </aside>
        </div>
      )}

      {/* Footer */}
      <footer className="border-t border-[#E5E7EB] bg-white">
        <div className="mx-auto max-w-5xl px-5 sm:px-8 h-14 flex items-center justify-between text-xs text-[#6B7280]">
          <span>BrainMate · Understand anything. Take action.</span>
          <span>Powered by AI · streaming</span>
        </div>
      </footer>
    </div>
  );
}

export default App;
