'use client';

import { useEffect, useRef, useState } from 'react';
import {
Brain,
Sparkles,
Copy,
Share2,
Loader2,
History,
Trash2,
X,
CheckCircle2,
ArrowRight,
Clock,
Zap,
MessageSquare,
Send,
Volume2,
VolumeX,
Pause,
Play,
Sun,
Moon,
Languages,
Download,
FileText,
FileDown,
Star
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

const MODES = [
{ id: 'kid', label: 'Kid Mode', hint: 'Super simple' },
{ id: 'student', label: 'Student Mode', hint: 'Clear & educational' },
{ id: 'pro', label: 'Pro Mode', hint: 'Precise & nuanced' }
];

const LANGUAGES = [
{ code: 'English', label: 'English', flag: '🇺🇸' },
{ code: 'Spanish', label: 'Español', flag: '🇪🇸' },
{ code: 'French', label: 'Français', flag: '🇫🇷' },
{ code: 'German', label: 'Deutsch', flag: '🇩🇪' },
{ code: 'Italian', label: 'Italiano', flag: '🇮🇹' },
{ code: 'Portuguese', label: 'Português', flag: '🇵🇹' },
{ code: 'Hindi', label: 'हिन्दी', flag: '🇮🇳' },
{ code: 'Mandarin Chinese', label: '中文', flag: '🇨🇳' },
{ code: 'Japanese', label: '日本語', flag: '🇯🇵' },
{ code: 'Korean', label: '한국어', flag: '🇰🇷' },
{ code: 'Arabic', label: 'العربية', flag: '🇸🇦' },
{ code: 'Russian', label: 'Русский', flag: '🇷🇺' }
];

const STORAGE_KEY = 'brainmate.history.v1';
const THEME_KEY = 'brainmate.theme';
const LANG_KEY = 'brainmate.language';

const copyText = async (text) => {
try {
await navigator.clipboard.writeText(text);
toast.success('Copied to clipboard');
} catch (e) {
toast.error('Could not copy');
}
};

const formatForShare = (r) => {
  if (!r) return '';

  const steps = (r.step_by_step || [])
    .map((s, i) => `${i + 1}. ${s}`)
    .join('\n');

  const plan = (r.action_plan || [])
    .map(
      (a, i) =>
        `${i + 1}. ${a.step}${a.time ? ` — ${a.time}` : ''}`
    )
    .join('\n');

  return [
    `BrainMate — ${r.topic}`,
    '',
    `Simple Explanation:\n${r.simple_explanation}`,
    '',
    `Real-Life Analogy:\n${r.real_life_analogy}`,
    '',
    `Step-by-Step:\n${steps}`,
    '',
    `Summary:\n${r.summary}`,
    '',
    `Action Plan:\n${plan}`,
    '',
    '— Generated by BrainMate'
  ].join('\n');
};

// Parse the section-tagged running buffer into a partial result.
// Handles incomplete sections gracefully (used while streaming).
function parsePartial(buffer) {
const out = {
simple_explanation: '',
real_life_analogy: '',
step_by_step: [],
summary: '',
action_plan: [],
active: null // which section is currently streaming
};

const sections = [
  { tag: 'SIMPLE', key: 'simple_explanation', type: 'text' },
  { tag: 'ANALOGY', key: 'real_life_analogy', type: 'text' },
  { tag: 'STEPS', key: 'step_by_step', type: 'bullets' },
  { tag: 'SUMMARY', key: 'summary', type: 'text' },
  { tag: 'ACTIONS', key: 'action_plan', type: 'actions' }
];

for (const s of sections) {
const openTag = `<<${s.tag}>>`;
const startIdx = buffer.indexOf(openTag);
if (startIdx === -1) continue;
const afterStart = startIdx + openTag.length;
const endIdx = buffer.indexOf('<<END>>', afterStart);
const isClosed = endIdx !== -1;
const raw = isClosed ? buffer.slice(afterStart, endIdx) : buffer.slice(afterStart);
const content = raw.replace(/^\n+/, '').replace(/\n+$/, '');

if (!isClosed) out.active = s.key;  

if (s.type === 'text') {  
  out[s.key] = content;  
} else if (s.type === 'bullets') {  
  out[s.key] = content  
    .split('\n')  
    .map((l) => l.replace(/^\s*[-*]\s*/, '').trim())  
    .filter(Boolean);  
} else if (s.type === 'actions') {  
  out[s.key] = content  
    .split('\n')  
    .map((l) => l.replace(/^\s*[-*]\s*/, '').trim())  
    .filter(Boolean)  
    .map((line) => {  
      const m = line.match(/^\[([^\]]+)\]\s*(.*)$/);  
      if (m) return { time: m[1].trim(), step: m[2].trim() };  
      return { time: '', step: line };  
    });  
}

}
return out;
}

function Card({ title, children, copyable, onCopy, streaming, speakable, isSpeaking, onSpeak, onStopSpeak }) {
return (
<div className="fade-in-up rounded-2xl border border-[var(--bm-border)] bg-[var(--bm-card)] p-6 sm:p-7 soft-card-shadow">
<div className="flex items-start justify-between gap-4 mb-3">
<div className="flex items-center gap-2">
<h3 className="text-[15px] font-semibold tracking-tight text-[var(--bm-text)]">{title}</h3>
{streaming && (
<span className="inline-flex items-center gap-1 text-[11px] text-[var(--bm-accent)] bg-[var(--bm-accent-soft)] border border-[var(--bm-accent-soft-border)] rounded-full px-2 py-0.5">
<span className="h-1.5 w-1.5 rounded-full bg-[var(--bm-accent)] animate-pulse" />
writing
</span>
)}
</div>
<div className="flex items-center gap-3 shrink-0">
{speakable && (
<button
onClick={isSpeaking ? onStopSpeak : onSpeak}
className={cn(
'inline-flex items-center gap-1.5 text-xs transition-colors',
isSpeaking ? 'text-[var(--bm-accent)]' : 'text-[var(--bm-text-soft)] hover:text-[var(--bm-text)]'
)}
aria-label={isSpeaking ? `Stop speaking ${title}` : `Listen to ${title}`}
>
{isSpeaking ? <VolumeX className="h-3.5 w-3.5" /> : <Volume2 className="h-3.5 w-3.5" />}
{isSpeaking ? 'Stop' : 'Listen'}
</button>
)}
{copyable && (
<button
onClick={onCopy}
className="inline-flex items-center gap-1.5 text-xs text-[var(--bm-text-soft)] hover:text-[var(--bm-text)] transition-colors"
aria-label={`Copy ${title}`}
>
<Copy className="h-3.5 w-3.5" />
Copy
</button>
)}
</div>
</div>
<div className="text-[15px] leading-relaxed text-[var(--bm-text)]">{children}</div>
</div>
);
}

function ModePill({ active, children, hint, onClick }) {
return (
<button
onClick={onClick}
className={cn(
'group relative px-4 py-2 rounded-xl text-sm font-medium transition-all border',
active
? 'bg-[var(--bm-pill-active)] text-[var(--bm-pill-active-text)] border-[var(--bm-pill-active)] shadow-sm'
: 'bg-[var(--bm-card)] text-[var(--bm-text)] border-[var(--bm-border)] hover:border-[var(--bm-text)]/30'
)}
>
<span>{children}</span>
<span
className={cn('ml-2 text-[11px]', active ? 'text-[var(--bm-pill-active-text)]/70' : 'text-[var(--bm-text-soft)]')}
>
· {hint}
</span>
</button>
);
}

function App() {
const [topic, setTopic] = useState('');
const [mode, setMode] = useState('student');
const [loading, setLoading] = useState(false);
const [streaming, setStreaming] = useState(false);
const [result, setResult] = useState(null);
const [activeSection, setActiveSection] = useState(null);
const [history, setHistory] = useState([]);
const [sidebarOpen, setSidebarOpen] = useState(false);
const abortRef = useRef(null);

// Chat state
const [chatMessages, setChatMessages] = useState([]); // [{role:'user'|'assistant', content:''}]
const [chatInput, setChatInput] = useState('');
const [chatStreaming, setChatStreaming] = useState(false);
const chatAbortRef = useRef(null);
const chatEndRef = useRef(null);

// Voice state
const [speaking, setSpeaking] = useState(false);
const [speakingWhat, setSpeakingWhat] = useState(null); // e.g. 'all' | 'summary' | key
const [voiceSupported, setVoiceSupported] = useState(false);

// Theme + language + export state
const [theme, setTheme] = useState('light');
const [language, setLanguage] = useState('English');
const [langOpen, setLangOpen] = useState(false);
const [exportOpen, setExportOpen] = useState(false);

// Cross-device user identity (anonymous "sync code")
const [userId, setUserId] = useState('');
const [historyLoading, setHistoryLoading] = useState(false);
const [showSyncCode, setShowSyncCode] = useState(false);
const [syncCodeInput, setSyncCodeInput] = useState('');

// Initialize / generate user_id, then load history from API
useEffect(() => {
let uid = '';
try {
uid = localStorage.getItem('brainmate.user_id') || '';
if (!uid) {
// Use crypto.randomUUID if available, fallback to manual
uid =
(typeof crypto !== 'undefined' && crypto.randomUUID && crypto.randomUUID()) ||
`${Date.now()}-${Math.random().toString(36).slice(2, 12)}`;
localStorage.setItem('brainmate.user_id', uid);
}
} catch (e) {
uid = ${Date.now()}-${Math.random().toString(36).slice(2, 12)};
}
setUserId(uid);
}, []);

// Load history when userId changes
useEffect(() => {
if (!userId) return;
let cancelled = false;
(async () => {
setHistoryLoading(true);
try {
fetch(`/api/history?user_id=${encodeURIComponent(userId)}`);
const data = await res.json();
if (!cancelled && Array.isArray(data?.items)) {
// Map server entries to existing UI shape
const items = data.items.map((it) => ({
id: it.id,
topic: it.topic,
mode: it.mode,
created_at: it.created_at,
favorite: !!it.favorite,
payload: it.payload
}));
setHistory(items);
}
} catch (e) {
// Silent: keep empty
} finally {
if (!cancelled) setHistoryLoading(false);
}
})();
return () => {
cancelled = true;
};
}, [userId]);

// Voice capability
useEffect(() => {
if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
setVoiceSupported(true);
}
return () => {
if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
window.speechSynthesis.cancel();
}
};
}, []);

// Theme + language load
useEffect(() => {
try {
const t =
localStorage.getItem(THEME_KEY) ||
(typeof window !== 'undefined' &&
window.matchMedia('(prefers-color-scheme: dark)').matches
? 'dark'
: 'light');
setTheme(t);
if (typeof document !== 'undefined') {
document.documentElement.classList.toggle('dark', t === 'dark');
}
const l = localStorage.getItem(LANG_KEY);
if (l) setLanguage(l);
} catch (e) {}
}, []);

const toggleTheme = () => {
const next = theme === 'dark' ? 'light' : 'dark';
setTheme(next);
try {
localStorage.setItem(THEME_KEY, next);
document.documentElement.classList.toggle('dark', next === 'dark');
} catch (e) {}
};

const changeLanguage = (code) => {
setLanguage(code);
setLangOpen(false);
try {
localStorage.setItem(LANG_KEY, code);
} catch (e) {}
};

// Auto-scroll chat
useEffect(() => {
if (chatEndRef.current) {
chatEndRef.current.scrollIntoView({ behavior: 'smooth', block: 'end' });
}
}, [chatMessages, chatStreaming]);

// Voice helpers
const stopSpeaking = () => {
if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
window.speechSynthesis.cancel();
}
setSpeaking(false);
setSpeakingWhat(null);
};

const speak = (text, tag = 'section') => {
if (!voiceSupported || !text) return;
// Cancel any ongoing
window.speechSynthesis.cancel();
// Split long text into chunks for reliability (some browsers cut off >200 chars)
const chunks = String(text).match(/[^.!?]+[.!?]+|[^.!?]+$/g) || [String(text)];
setSpeaking(true);
setSpeakingWhat(tag);
let idx = 0;
const playNext = () => {
if (idx >= chunks.length) {
setSpeaking(false);
setSpeakingWhat(null);
return;
}
const u = new SpeechSynthesisUtterance(chunks[idx].trim());
u.rate = 1.0;
u.pitch = 1.0;
u.volume = 1.0;
u.onend = () => {
idx += 1;
playNext();
};
u.onerror = () => {
setSpeaking(false);
setSpeakingWhat(null);
};
window.speechSynthesis.speak(u);
};
playNext();
};

const speakAll = (r) => {
if (!r) return;
const parts = [
r.simple_explanation,
r.real_life_analogy,
...(r.step_by_step || []),
r.summary
].filter(Boolean);
speak(parts.join('. '), 'all');
};

const persistHistory = (next) => {
setHistory(next);
};

const saveToHistory = async (entry) => {
// Optimistic UI update
setHistory((prev) => [entry, ...prev].slice(0, 50));
if (!userId) return;
try {
const res = await fetch('/api/history', {
method: 'POST',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify({
user_id: userId,
id: entry.id,
created_at: entry.created_at,
payload: entry.payload
})
});
if (!res.ok) {
const err = await res.json().catch(() => ({}));
console.warn('Failed to save history:', err);
}
} catch (e) {
console.warn('Save history error:', e);
}
};

const handleExplain = async (overrideTopic, overrideMode) => {
const t = (overrideTopic ?? topic).trim();
const m = overrideMode ?? mode;
if (!t) {
toast.error('Type something to explain');
return;
}

// Cancel any in-flight stream  
if (abortRef.current) {  
  try {  
    abortRef.current.abort();  
  } catch (e) {}  
}  
// Stop any speaking and reset chat for the new topic  
stopSpeaking();  
setChatMessages([]);  
if (chatAbortRef.current) {  
  try {  
    chatAbortRef.current.abort();  
  } catch (e) {}  
  chatAbortRef.current = null;  
}  
setChatStreaming(false);  

const ctrl = new AbortController();  
abortRef.current = ctrl;  

setLoading(true);  
setStreaming(true);  
setResult({
  topic: t,
  mode: m,
  hook: '',
  simple_explanation: '',
  exam: '',
  formulas: [],
  step_by_step: [],
  mistakes: [],
  revision: '',
  next: []
});
setActiveSection('simple_explanation');  

let buffer = '';  
let rafPending = false;  
const flushUpdate = () => {  
  rafPending = false;  
  const partial = parsePartial(buffer);  
  setResult((prev) => ({
  ...(prev || {}),
  topic: t,
  mode: m,
  hook: partial.hook,
  simple_explanation: partial.simple_explanation,
  exam: partial.exam,
  formulas: partial.formulas,
  step_by_step: partial.step_by_step,
  mistakes: partial.mistakes,
  revision: partial.revision,
  next: partial.next
}));
  setActiveSection(partial.active);  
};  
const scheduleFlush = () => {  
  if (rafPending) return;  
  rafPending = true;  
  if (typeof requestAnimationFrame !== 'undefined') {  
    requestAnimationFrame(flushUpdate);  
  } else {  
    setTimeout(flushUpdate, 16);  
  }  
};  

try {  
  const res = await fetch('/api/explain/stream', {  
    method: 'POST',  
    headers: { 'Content-Type': 'application/json' },  
    body: JSON.stringify({ topic: t, mode: m, language }),  
    signal: ctrl.signal  
  });  

  if (!res.ok || !res.body) {  
    const errBody = await res.json().catch(() => ({}));  
    throw new Error(errBody?.error || `Request failed (${res.status})`);  
  }  

  const reader = res.body.getReader();  
  const decoder = new TextDecoder();  
  let sseBuf = '';  

  // Read SSE stream: events separated by blank line  
  while (true) {  
    const { value, done } = await reader.read();  
    if (done) break;  
    sseBuf += decoder.decode(value, { stream: true });  

    let sepIdx;  
    while ((sepIdx = sseBuf.indexOf('\n\n')) !== -1) {  
      const chunk = sseBuf.slice(0, sepIdx);  
      sseBuf = sseBuf.slice(sepIdx + 2);  

      let evt = 'message';  
      let dataLine = '';  
      for (const line of chunk.split('\n')) {  
        if (line.startsWith('event:')) evt = line.slice(6).trim();  
        else if (line.startsWith('data:')) dataLine += line.slice(5).trim();  
      }  
      if (!dataLine) continue;  

      if (evt === 'token') {  
        try {  
          const { text } = JSON.parse(dataLine);  
          if (typeof text === 'string') {  
            buffer += text;  
            scheduleFlush();  
          }  
        } catch (e) {}  
      } else if (evt === 'done') {  
        // Final parse  
        flushUpdate();  
      } else if (evt === 'error') {  
        try {  
          const { message } = JSON.parse(dataLine);  
          throw new Error(message || 'Stream error');  
        } catch (e) {  
          throw e;  
        }  
      }  
    }  
  }  
  // Final flush and save  
  flushUpdate();  
  const finalPartial = parsePartial(buffer);  
  const finalResult = {
  topic: t,
  mode: m,
  language,
  generated_at: new Date().toISOString(),
  hook: finalPartial.hook,
  simple_explanation: finalPartial.simple_explanation,
  exam: finalPartial.exam,
  formulas: finalPartial.formulas,
  step_by_step: finalPartial.step_by_step,
  mistakes: finalPartial.mistakes,
  revision: finalPartial.revision,
  next: finalPartial.next
};
  setResult(finalResult);  
  setActiveSection(null);  

  if (  
    finalResult.simple_explanation ||  
    finalResult.summary ||  
    finalResult.step_by_step.length  
  ) {  
    saveToHistory({  
      id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,  
      topic: t,  
      mode: m,  
      created_at: new Date().toISOString(),  
      payload: finalResult  
    });  
  }  
} catch (err) {  
  if (err?.name === 'AbortError') {  
    // ignore — user cancelled  
  } else {  
    toast.error(err?.message || 'Failed to generate');  
  }  
} finally {  
  setLoading(false);  
  setStreaming(false);  
  abortRef.current = null;  
}

};

const handleStop = () => {
if (abortRef.current) {
abortRef.current.abort();
abortRef.current = null;
}
setStreaming(false);
setLoading(false);
};

// -------- Follow-up chat --------
const sendChatMessage = async () => {
const text = chatInput.trim();
if (!text || chatStreaming || !result) return;

// Cancel any in-flight  
if (chatAbortRef.current) {  
  try {  
    chatAbortRef.current.abort();  
  } catch (e) {}  
}  
const ctrl = new AbortController();  
chatAbortRef.current = ctrl;  

const userMsg = { role: 'user', content: text };  
const assistantMsg = { role: 'assistant', content: '' };  
const nextMsgs = [...chatMessages, userMsg, assistantMsg];  
setChatMessages(nextMsgs);  
setChatInput('');  
setChatStreaming(true);  

// Build context from current explanation  
const ctx = [  
  result.simple_explanation ? `Simple explanation: ${result.simple_explanation}` : '',  
  result.real_life_analogy ? `Analogy: ${result.real_life_analogy}` : '',  
  result.step_by_step?.length ? `Steps: ${result.step_by_step.join(' | ')}` : '',  
  result.summary ? `Summary: ${result.summary}` : ''  
]  
  .filter(Boolean)  
  .join('\n');  

// Messages to send: everything except the empty assistant placeholder  
const sendMessages = nextMsgs  
  .slice(0, -1)  
  .map((m) => ({ role: m.role, content: m.content }));  

try {  
  const res = await fetch('/api/chat/stream', {  
    method: 'POST',  
    headers: { 'Content-Type': 'application/json' },  
    body: JSON.stringify({  
      topic: result.topic,  
      mode: result.mode,  
      language: result.language || language,  
      context: ctx,  
      messages: sendMessages  
    }),  
    signal: ctrl.signal  
  });  
  if (!res.ok || !res.body) {  
    const errBody = await res.json().catch(() => ({}));  
    throw new Error(errBody?.error || `Request failed (${res.status})`);  
  }  

  const reader = res.body.getReader();  
  const decoder = new TextDecoder();  
  let sseBuf = '';  
  let assistantText = '';  

  while (true) {  
    const { value, done } = await reader.read();  
    if (done) break;  
    sseBuf += decoder.decode(value, { stream: true });  
    let sepIdx;  
    while ((sepIdx = sseBuf.indexOf('\n\n')) !== -1) {  
      const chunk = sseBuf.slice(0, sepIdx);  
      sseBuf = sseBuf.slice(sepIdx + 2);  
      let evt = 'message';  
      let dataLine = '';  
      for (const line of chunk.split('\n')) {  
        if (line.startsWith('event:')) evt = line.slice(6).trim();  
        else if (line.startsWith('data:')) dataLine += line.slice(5).trim();  
      }  
      if (!dataLine) continue;  
      if (evt === 'token') {  
        try {  
          const { text: t } = JSON.parse(dataLine);  
          if (typeof t === 'string') {  
            assistantText += t;  
            setChatMessages((prev) => {  
              const copy = prev.slice();  
              const last = copy[copy.length - 1];  
              if (last && last.role === 'assistant') {  
                copy[copy.length - 1] = { ...last, content: assistantText };  
              }  
              return copy;  
            });  
          }  
        } catch (e) {}  
      } else if (evt === 'error') {  
        try {  
          const { message } = JSON.parse(dataLine);  
          throw new Error(message || 'Chat error');  
        } catch (e) {  
          throw e;  
        }  
      }  
    }  
  }  
} catch (err) {  
  if (err?.name !== 'AbortError') {  
    toast.error(err?.message || 'Chat failed');  
    // Replace empty assistant bubble with error marker  
    setChatMessages((prev) => {  
      const copy = prev.slice();  
      const last = copy[copy.length - 1];  
      if (last && last.role === 'assistant' && !last.content) {  
        copy[copy.length - 1] = {  
          ...last,  
          content: '⚠️ Could not generate a reply. Try again.'  
        };  
      }  
      return copy;  
    });  
  }  
} finally {  
  setChatStreaming(false);  
  chatAbortRef.current = null;  
}

};

// -------- Export --------
const buildMarkdown = (r) => {
if (!r) return '';
const steps = (r.step_by_step || []).map((s, i) => ${i + 1}. ${s}).join('\n');
const plan = (r.action_plan || [])
.map((a, i) => ${i + 1}. **${a.step}**${a.time ?  (${a.time}) : ''})
.join('\n');
return [
'# BrainMate — ${r.topic}`,
,   `_Mode: ${r.mode}${r.language ? ` · Language: ${r.language}` : ''}${r.generated_at ? ` · Generated: ${new Date(r.generated_at).toLocaleString()}` : ''}_`,   ,
## Simple Explanation,
r.simple_explanation || '',
,   `## Real-Life Analogy`,   r.real_life_analogy || '',   ,
## Step-by-Step Breakdown,
steps,
,   `## Quick Summary`,   r.summary || '',   ,
## What should you do next?,
plan,
``,
---,
Generated by BrainMate
].join('\n');
};

const downloadBlob = (filename, content, mime) => {
const blob = new Blob([content], { type: mime });
const url = URL.createObjectURL(blob);
const a = document.createElement('a');
a.href = url;
a.download = filename;
document.body.appendChild(a);
a.click();
document.body.removeChild(a);
setTimeout(() => URL.revokeObjectURL(url), 1000);
};

const safeFilename = (s) =>
(s || 'brainmate')
.replace(/[^\p{L}\p{N}_-]+/gu, '-')
.replace(/^-+|-+$/g, '')
.slice(0, 60) || 'brainmate';

const exportMarkdown = () => {
if (!result) return;
const md = buildMarkdown(result);
downloadBlob(brainmate-${safeFilename(result.topic)}.md, md, 'text/markdown;charset=utf-8');
toast.success('Markdown downloaded');
setExportOpen(false);
};

const exportPDF = async () => {
if (!result) return;
try {
const { jsPDF } = await import('jspdf');
const doc = new jsPDF({ unit: 'pt', format: 'a4' });
const pageW = doc.internal.pageSize.getWidth();
const pageH = doc.internal.pageSize.getHeight();
const marginX = 56;
const maxW = pageW - marginX * 2;
let y = 64;

const ensureSpace = (h) => {  
    if (y + h > pageH - 56) {  
      doc.addPage();  
      y = 64;  
    }  
  };  

  const writeWrapped = (text, opts = {}) => {  
    const { size = 11, bold = false, color = [11, 11, 15], gap = 4, indent = 0 } = opts;  
    doc.setFont('helvetica', bold ? 'bold' : 'normal');  
    doc.setFontSize(size);  
    doc.setTextColor(color[0], color[1], color[2]);  
    const lines = doc.splitTextToSize(text || '', maxW - indent);  
    const lh = size * 1.35;  
    for (const line of lines) {  
      ensureSpace(lh);  
      doc.text(line, marginX + indent, y);  
      y += lh;  
    }  
    y += gap;  
  };  

  // Title  
  writeWrapped(`BrainMate — ${result.topic || ''}`, { size: 18, bold: true, gap: 6 });  
  const meta =  
    `Mode: ${result.mode || ''}` +  
    (result.language ? ` · Language: ${result.language}` : '') +  
    (result.generated_at ? ` · ${new Date(result.generated_at).toLocaleString()}` : '');  
  writeWrapped(meta, { size: 9, color: [107, 114, 128], gap: 14 });  

  const writeSection = (heading, body) => {  
    writeWrapped(heading, { size: 13, bold: true, gap: 4 });  
    writeWrapped(body, { size: 11, gap: 12 });  
  };  

  writeSection('Simple Explanation', result.simple_explanation || '');  
  writeSection('Real-Life Analogy', result.real_life_analogy || '');  

  writeWrapped('Step-by-Step Breakdown', { size: 13, bold: true, gap: 4 });  
  (result.step_by_step || []).forEach((s, i) => {  
    writeWrapped(`${i + 1}. ${s}`, { size: 11, gap: 2, indent: 12 });  
  });  
  y += 8;  

  writeSection('Quick Summary', result.summary || '');  

  writeWrapped('What should you do next?', { size: 13, bold: true, gap: 4 });  
  (result.action_plan || []).forEach((a, i) => {  
    const line = `${i + 1}. ${a.step}${a.time ? `  (${a.time})` : ''}`;  
    writeWrapped(line, { size: 11, gap: 2, indent: 12 });  
  });  
  y += 12;  
  writeWrapped('— Generated by BrainMate', {  
    size: 9,  
    color: [156, 163, 175],  
    gap: 0  
  });  

  doc.save(`brainmate-${safeFilename(result.topic)}.pdf`);  
  toast.success('PDF downloaded');  
  setExportOpen(false);  
} catch (e) {  
  console.error(e);  
  toast.error('Could not export PDF');  
}

};

const handleShare = async () => {
if (!result) return;
const text = formatForShare(result);
const shareData = {
title: BrainMate — ${result.topic},
text,
url: typeof window !== 'undefined' ? window.location.href : undefined
};
try {
if (typeof navigator !== 'undefined' && navigator.share) {
await navigator.share(shareData);
} else {
await navigator.clipboard.writeText(text);
toast.success('Copied share text to clipboard');
}
} catch (e) {
// ignore cancel
}
};

const loadFromHistory = (entry) => {
stopSpeaking();
setChatMessages([]);
setTopic(entry.topic);
setMode(entry.mode);
setResult(entry.payload);
setActiveSection(null);
setSidebarOpen(false);
if (typeof window !== 'undefined') {
window.scrollTo({ top: 0, behavior: 'smooth' });
}
};

const deleteFromHistory = async (id) => {
// Optimistic
setHistory((prev) => prev.filter((h) => h.id !== id));
if (!userId) return;
try {
await fetch(
/api/history/${encodeURIComponent(id)}?user_id=${encodeURIComponent(userId)},
{ method: 'DELETE' }
);
} catch (e) {
console.warn('Delete history error:', e);
}
};

const toggleFavorite = async (id) => {
let nextFav = false;
// Optimistic + re-sort (favorites first)
setHistory((prev) => {
const updated = prev.map((h) => {
if (h.id === id) {
nextFav = !h.favorite;
return { ...h, favorite: nextFav };
}
return h;
});
const favs = updated.filter((h) => h.favorite);
const rest = updated.filter((h) => !h.favorite);
return [...favs, ...rest];
});
if (!userId) return;
try {
await fetch(/api/history/${encodeURIComponent(id)}/favorite, {
method: 'POST',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify({ user_id: userId, favorite: nextFav })
});
} catch (e) {
console.warn('Favorite error:', e);
}
};

const clearHistory = async () => {
setHistory([]);
if (!userId) return;
try {
await fetch(/api/history?user_id=${encodeURIComponent(userId)}, {
method: 'DELETE'
});
} catch (e) {
console.warn('Clear history error:', e);
}
};

// Sync code (cross-device): apply a pasted user_id
const applySyncCode = async () => {
const code = (syncCodeInput || '').trim();
if (!code) {
toast.error('Paste a sync code');
return;
}
if (code === userId) {
toast.message('That is already your current sync code');
return;
}
try {
localStorage.setItem('brainmate.user_id', code);
setUserId(code);
setSyncCodeInput('');
setShowSyncCode(false);
toast.success('Sync code applied — loading history…');
} catch (e) {
toast.error('Could not apply sync code');
}
};

const hasAnyContent =
!!result &&
(result.simple_explanation ||
result.real_life_analogy ||
(result.step_by_step && result.step_by_step.length) ||
result.summary ||
(result.action_plan && result.action_plan.length));

return (
<div className="min-h-screen bg-[var(--bm-bg)]">
{/* Top bar /}
<header className="sticky top-0 z-20 bg-[var(--bm-bg)]/80 backdrop-blur border-b border-[var(--bm-border)]">
<div className="mx-auto max-w-5xl px-5 sm:px-8 h-14 flex items-center justify-between">
<div className="flex items-center gap-2">
<div className="h-7 w-7 rounded-lg bg-[var(--bm-text)] flex items-center justify-center">
<Brain className="h-4 w-4 text-[var(--bm-card)]" />
</div>
<span className="font-semibold tracking-tight text-[15px]">BrainMate</span>
</div>
<div className="flex items-center gap-3 sm:gap-4">
{/ Language picker */}
<div className="relative">
<button
onClick={() => setLangOpen((o) => !o)}
className="inline-flex items-center gap-1.5 text-sm text-[var(--bm-text)] hover:text-[var(--bm-accent)] transition-colors"
aria-label="Change language"
>
<Languages className="h-4 w-4" />
<span className="hidden sm:inline text-[13px]">
{LANGUAGES.find((l) => l.code === language)?.label || language}
</span>
<span className="sm:hidden text-[15px]">
{LANGUAGES.find((l) => l.code === language)?.flag || '🌐'}
</span>
</button>
{langOpen && (
<>
<div className="fixed inset-0 z-10" onClick={() => setLangOpen(false)} />
<div className="absolute right-0 mt-2 w-56 rounded-xl border border-[var(--bm-border)] bg-[var(--bm-card)] shadow-lg overflow-hidden z-20">
<div className="max-h-80 overflow-y-auto py-1">
{LANGUAGES.map((l) => (
<button
key={l.code}
onClick={() => changeLanguage(l.code)}
className={cn(
'w-full flex items-center gap-3 px-3 py-2 text-sm text-left transition-colors',
language === l.code
? 'bg-[var(--bm-subtle)] text-[var(--bm-text)]'
: 'text-[var(--bm-text)] hover:bg-[var(--bm-subtle)]'
)}
>
<span className="text-base leading-none">{l.flag}</span>
<span className="flex-1">{l.label}</span>
{language === l.code && (
<CheckCircle2 className="h-3.5 w-3.5 text-[var(--bm-accent)]" />
)}
</button>
))}
</div>
</div>
</>
)}
</div>

{/* Theme toggle */}  
        <button  
          onClick={toggleTheme}  
          className="inline-flex items-center justify-center h-8 w-8 rounded-lg border border-[var(--bm-border)] bg-[var(--bm-card)] text-[var(--bm-text)] hover:border-[var(--bm-text)]/30 transition-colors"  
          aria-label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'}  
        >  
          {theme === 'dark' ? (  
            <Sun className="h-4 w-4" />  
          ) : (  
            <Moon className="h-4 w-4" />  
          )}  
        </button>  

        <button  
          onClick={() => setSidebarOpen(true)}  
          className="inline-flex items-center gap-2 text-sm text-[var(--bm-text)] hover:text-[var(--bm-accent)] transition-colors"  
        >  
          <History className="h-4 w-4" />  
          <span className="hidden sm:inline">  
            History {history.length > 0 && <span className="text-[var(--bm-text-soft)]">({history.length})</span>}  
          </span>  
        </button>  
      </div>  
    </div>  
  </header>  

  {/* Main */}  
  <main className="mx-auto max-w-3xl px-5 sm:px-8 pt-14 sm:pt-20 pb-24">  
    {/* Hero */}  
    <div className="text-center mb-10 sm:mb-12 fade-in">  
      <div className="inline-flex items-center gap-2 text-xs text-[var(--bm-text-soft)] bg-[var(--bm-card)] border border-[var(--bm-border)] rounded-full px-3 py-1 mb-6">  
        <Sparkles className="h-3.5 w-3.5 text-[var(--bm-accent)]" />  
        AI-powered clarity · streaming live  
      </div>  
      <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-[var(--bm-text)]">  
        BrainMate  
      </h1>  
      <p className="mt-3 text-[var(--bm-text-soft)] text-base sm:text-lg">  
        Understand anything. Take action.  
      </p>  
    </div>  

    {/* Input card */}  
    <div className="rounded-2xl border border-[var(--bm-border)] bg-[var(--bm-card)] p-4 sm:p-5 soft-card-shadow fade-in">  
      <Textarea  
        value={topic}  
        onChange={(e) => setTopic(e.target.value)}  
        placeholder="What do you want to understand? e.g. How does a black hole work?"  
        className="min-h-[96px] resize-none border-0 shadow-none focus-visible:ring-0 text-[16px] placeholder:text-[var(--bm-text-faint)] px-1"  
        onKeyDown={(e) => {  
          if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {  
            e.preventDefault();  
            handleExplain();  
          }  
        }}  
      />  
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mt-3 pt-3 border-t border-[var(--bm-subtle)]">  
        <div className="flex flex-wrap items-center gap-2">  
          {MODES.map((m) => (  
            <ModePill  
              key={m.id}  
              active={mode === m.id}  
              hint={m.hint}  
              onClick={() => setMode(m.id)}  
            >  
              {m.label}  
            </ModePill>  
          ))}  
        </div>  
        {streaming ? (  
          <Button  
            onClick={handleStop}  
            variant="outline"  
            className="rounded-xl h-10 px-5 font-medium border-[var(--bm-border)]"  
          >  
            <X className="h-4 w-4 mr-2" />  
            Stop  
          </Button>  
        ) : (  
          <Button  
            onClick={() => handleExplain()}  
            disabled={loading || !topic.trim()}  
            className="bg-[var(--bm-accent)] hover:bg-[var(--bm-accent-hover)] text-white rounded-xl h-10 px-5 font-medium shadow-sm"  
          >  
            {loading ? (  
              <>  
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />  
                Thinking...  
              </>  
            ) : (  
              <>  
                Explain  
                <ArrowRight className="h-4 w-4 ml-2" />  
              </>  
            )}  
          </Button>  
        )}  
      </div>  
      <div className="mt-2 text-[11px] text-[var(--bm-text-faint)] px-1 flex items-center gap-1.5">  
        <Zap className="h-3 w-3" />  
        Tip: press ⌘/Ctrl + Enter to explain · streams in real time  
      </div>  
    </div>  

    {/* Results */}  
    {(streaming || hasAnyContent) && (  
      <div className="mt-8 space-y-4">  
        {/* Actions bar */}  
        {result && (  
          <div className="flex items-center justify-between fade-in">  
            <div className="text-sm text-[var(--bm-text-soft)] truncate">  
              <span className="text-[var(--bm-text)] font-medium">{result.topic}</span> · {result.mode} mode  
            </div>  
            {hasAnyContent && !streaming && (  
              <div className="flex items-center gap-2 shrink-0 ml-3">  
                {voiceSupported && (  
                  <button  
                    onClick={() => (speaking && speakingWhat === 'all' ? stopSpeaking() : speakAll(result))}  
                    className={cn(  
                      'inline-flex items-center gap-1.5 text-xs bg-[var(--bm-card)] border rounded-lg px-3 py-1.5 transition-colors',  
                      speaking && speakingWhat === 'all'  
                        ? 'text-[var(--bm-accent)] border-[var(--bm-accent-soft-border)] bg-[var(--bm-accent-soft)]'  
                        : 'text-[var(--bm-text)] border-[var(--bm-border)] hover:border-[var(--bm-text)]/30'  
                    )}  
                    aria-label={speaking && speakingWhat === 'all' ? 'Stop speaking' : 'Listen to all'}  
                  >  
                    {speaking && speakingWhat === 'all' ? (  
                      <>  
                        <VolumeX className="h-3.5 w-3.5" /> Stop  
                      </>  
                    ) : (  
                      <>  
                        <Volume2 className="h-3.5 w-3.5" /> Listen  
                      </>  
                    )}  
                  </button>  
                )}  
                <button  
                  onClick={() => copyText(formatForShare(result))}  
                  className="inline-flex items-center gap-1.5 text-xs text-[var(--bm-text)] bg-[var(--bm-card)] border border-[var(--bm-border)] rounded-lg px-3 py-1.5 hover:border-[var(--bm-text)]/30 transition-colors"  
                >  
                  <Copy className="h-3.5 w-3.5" /> Copy all  
                </button>  

                {/* Export menu */}  
                <div className="relative">  
                  <button  
                    onClick={() => setExportOpen((o) => !o)}  
                    className="inline-flex items-center gap-1.5 text-xs text-[var(--bm-text)] bg-[var(--bm-card)] border border-[var(--bm-border)] rounded-lg px-3 py-1.5 hover:border-[var(--bm-text)]/30 transition-colors"  
                  >  
                    <Download className="h-3.5 w-3.5" /> Export  
                  </button>  
                  {exportOpen && (  
                    <>  
                      <div className="fixed inset-0 z-10" onClick={() => setExportOpen(false)} />  
                      <div className="absolute right-0 mt-2 w-48 rounded-xl border border-[var(--bm-border)] bg-[var(--bm-card)] shadow-lg overflow-hidden z-20 py-1">  
                        <button  
                          onClick={exportMarkdown}  
                          className="w-full flex items-center gap-2 px-3 py-2 text-sm text-left text-[var(--bm-text)] hover:bg-[var(--bm-subtle)] transition-colors"  
                        >  
                          <FileText className="h-4 w-4 text-[var(--bm-text-soft)]" />  
                          Markdown (.md)  
                        </button>  
                        <button  
                          onClick={exportPDF}  
                          className="w-full flex items-center gap-2 px-3 py-2 text-sm text-left text-[var(--bm-text)] hover:bg-[var(--bm-subtle)] transition-colors"  
                        >  
                          <FileDown className="h-4 w-4 text-[var(--bm-text-soft)]" />  
                          PDF (.pdf)  
                        </button>  
                      </div>  
                    </>  
                  )}  
                </div>  

                <button  
                  onClick={handleShare}  
                  className="inline-flex items-center gap-1.5 text-xs text-[var(--bm-text)] bg-[var(--bm-card)] border border-[var(--bm-border)] rounded-lg px-3 py-1.5 hover:border-[var(--bm-text)]/30 transition-colors"  
                >  
                  <Share2 className="h-3.5 w-3.5" /> Share  
                </button>  
              </div>  
            )}  
          </div>  
        )}  

        {(result?.simple_explanation || activeSection === 'simple_explanation') && (  
          <Card  
            title="Simple Explanation"  
            copyable={!streaming}  
            streaming={streaming && activeSection === 'simple_explanation'}  
            onCopy={() => copyText(result.simple_explanation)}  
            speakable={voiceSupported && !streaming && !!result?.simple_explanation}  
            isSpeaking={speaking && speakingWhat === 'simple_explanation'}  
            onSpeak={() => speak(result.simple_explanation, 'simple_explanation')}  
            onStopSpeak={stopSpeaking}  
          >  
            <p className="whitespace-pre-wrap">  
              {result.simple_explanation || <span className="text-[var(--bm-text-faint)]">Writing…</span>}  
              {streaming && activeSection === 'simple_explanation' && (  
                <span className="inline-block w-[2px] h-4 bg-[var(--bm-accent)] align-middle ml-0.5 animate-pulse" />  
              )}  
            </p>  
          </Card>  
        )}  

        {(result?.real_life_analogy || activeSection === 'real_life_analogy') && (  
          <Card  
            title="Real-Life Analogy"  
            copyable={!streaming}  
            streaming={streaming && activeSection === 'real_life_analogy'}  
            onCopy={() => copyText(result.real_life_analogy)}  
            speakable={voiceSupported && !streaming && !!result?.real_life_analogy}  
            isSpeaking={speaking && speakingWhat === 'real_life_analogy'}  
            onSpeak={() => speak(result.real_life_analogy, 'real_life_analogy')}  
            onStopSpeak={stopSpeaking}  
          >  
            <p className="whitespace-pre-wrap">  
              {result.real_life_analogy || <span className="text-[var(--bm-text-faint)]">Writing…</span>}  
              {streaming && activeSection === 'real_life_analogy' && (  
                <span className="inline-block w-[2px] h-4 bg-[var(--bm-accent)] align-middle ml-0.5 animate-pulse" />  
              )}  
            </p>  
          </Card>  
        )}  

        {((result?.step_by_step && result.step_by_step.length > 0) || activeSection === 'step_by_step') && (  
          <Card  
            title="Step-by-Step Breakdown"  
            copyable={!streaming}  
            streaming={streaming && activeSection === 'step_by_step'}  
            onCopy={() =>  
              copyText((result.step_by_step || []).map((s, i) => `${i + 1}. ${s}`).join('\n'))  
            }  
          >  
            <ul className="space-y-2.5">  
              {(result?.step_by_step || []).map((s, i) => (  
                <li key={i} className="flex gap-3 fade-in">  
                  <span className="mt-0.5 text-[12px] font-semibold text-[var(--bm-accent)] min-w-[20px]">  
                    {String(i + 1).padStart(2, '0')}  
                  </span>  
                  <span>{s}</span>  
                </li>  
              ))}  
              {streaming && activeSection === 'step_by_step' && (!result?.step_by_step || result.step_by_step.length === 0) && (  
                <li className="text-[var(--bm-text-faint)]">Writing…</li>  
              )}  
            </ul>  
          </Card>  
        )}  

        {(result?.summary || activeSection === 'summary') && (  
          <Card  
            title="Quick Summary"  
            copyable={!streaming}  
            streaming={streaming && activeSection === 'summary'}  
            onCopy={() => copyText(result.summary)}  
            speakable={voiceSupported && !streaming && !!result?.summary}  
            isSpeaking={speaking && speakingWhat === 'summary'}  
            onSpeak={() => speak(result.summary, 'summary')}  
            onStopSpeak={stopSpeaking}  
          >  
            <p className="whitespace-pre-wrap">  
              {result.summary || <span className="text-[var(--bm-text-faint)]">Writing…</span>}  
              {streaming && activeSection === 'summary' && (  
                <span className="inline-block w-[2px] h-4 bg-[var(--bm-accent)] align-middle ml-0.5 animate-pulse" />  
              )}  
            </p>  
          </Card>  
        )}  

        {((result?.action_plan && result.action_plan.length > 0) || activeSection === 'action_plan') && (  
          <Card  
            title="What should you do next?"  
            copyable={!streaming}  
            streaming={streaming && activeSection === 'action_plan'}  
            onCopy={() =>  
              copyText(  
                (result.action_plan || [])  
                  .map((a, i) => `${i + 1}. ${a.step}${a.time ? ` — ${a.time}` : ''}`)  
                  .join('\n')  
              )  
            }  
          >  
            <ul className="space-y-3">  
              {(result?.action_plan || []).map((a, i) => (  
                <li  
                  key={i}  
                  className="flex items-start gap-3 pb-3 last:pb-0 border-b last:border-b-0 border-[var(--bm-subtle)] fade-in"  
                >  
                  <CheckCircle2 className="h-4 w-4 mt-0.5 text-[var(--bm-accent)] shrink-0" />  
                  <div className="flex-1">  
                    <div className="text-[15px] text-[var(--bm-text)]">{a.step}</div>  
                    {a.time && (  
                      <div className="mt-1 inline-flex items-center gap-1 text-[12px] text-[var(--bm-text-soft)]">  
                        <Clock className="h-3 w-3" />  
                        {a.time}  
                      </div>  
                    )}  
                  </div>  
                </li>  
              ))}  
              {streaming && activeSection === 'action_plan' && (!result?.action_plan || result.action_plan.length === 0) && (  
                <li className="text-[var(--bm-text-faint)]">Writing…</li>  
              )}  
            </ul>  
          </Card>  
        )}  

        {/* Follow-up chat */}  
        {hasAnyContent && !streaming && (  
          <div className="mt-4 rounded-2xl border border-[var(--bm-border)] bg-[var(--bm-card)] soft-card-shadow fade-in-up overflow-hidden">  
            <div className="flex items-center gap-2 px-6 pt-5 pb-3 border-b border-[var(--bm-subtle)]">  
              <MessageSquare className="h-4 w-4 text-[var(--bm-accent)]" />  
              <h3 className="text-[15px] font-semibold tracking-tight text-[var(--bm-text)]">  
                Ask a follow-up  
              </h3>  
              <span className="text-xs text-[var(--bm-text-soft)]">  
                about "{result.topic}"  
              </span>  
            </div>  

            {chatMessages.length > 0 && (  
              <div className="px-6 py-4 space-y-4 max-h-[480px] overflow-y-auto">  
                {chatMessages.map((m, i) => (  
                  <div  
                    key={i}  
                    className={cn(  
                      'flex',  
                      m.role === 'user' ? 'justify-end' : 'justify-start'  
                    )}  
                  >  
                    <div  
                      className={cn(  
                        'max-w-[85%] rounded-2xl px-4 py-2.5 text-[14px] leading-relaxed whitespace-pre-wrap',  
                        m.role === 'user'  
                          ? 'bg-[var(--bm-pill-active)] text-[var(--bm-pill-active-text)] rounded-br-md'  
                          : 'bg-[var(--bm-subtle)] text-[var(--bm-text)] rounded-bl-md'  
                      )}  
                    >  
                      {m.content || (  
                        <span className="inline-flex items-center gap-2 text-[var(--bm-text-soft)]">  
                          <Loader2 className="h-3.5 w-3.5 animate-spin" />  
                          Thinking…  
                        </span>  
                      )}  
                      {m.role === 'assistant' &&  
                        chatStreaming &&  
                        i === chatMessages.length - 1 &&  
                        m.content && (  
                          <span className="inline-block w-[2px] h-4 bg-[var(--bm-accent)] align-middle ml-0.5 animate-pulse" />  
                        )}  
                    </div>  
                  </div>  
                ))}  
                <div ref={chatEndRef} />  
              </div>  
            )}  

            <div className="px-4 sm:px-5 py-3 border-t border-[var(--bm-subtle)] bg-[var(--bm-subtle)]">  
              <div className="flex items-end gap-2">  
                <Textarea  
                  value={chatInput}  
                  onChange={(e) => setChatInput(e.target.value)}  
                  placeholder={  
                    chatMessages.length === 0  
                      ? 'Ask anything about this explanation…'  
                      : 'Continue the conversation…'  
                  }  
                  className="min-h-[44px] max-h-[120px] resize-none bg-[var(--bm-card)] border border-[var(--bm-border)] rounded-xl text-[14px] focus-visible:ring-1 focus-visible:ring-[var(--bm-accent)]"  
                  onKeyDown={(e) => {  
                    if (e.key === 'Enter' && !e.shiftKey) {  
                      e.preventDefault();  
                      sendChatMessage();  
                    }  
                  }}  
                  disabled={chatStreaming}  
                />  
                <Button  
                  onClick={sendChatMessage}  
                  disabled={chatStreaming || !chatInput.trim()}  
                  className="bg-[var(--bm-accent)] hover:bg-[var(--bm-accent-hover)] text-white rounded-xl h-[44px] w-[44px] p-0 shrink-0"  
                  aria-label="Send"  
                >  
                  {chatStreaming ? (  
                    <Loader2 className="h-4 w-4 animate-spin" />  
                  ) : (  
                    <Send className="h-4 w-4" />  
                  )}  
                </Button>  
              </div>  
              {chatMessages.length === 0 && (  
                <div className="mt-2 flex flex-wrap gap-1.5">  
                  {[  
                    'Give me a concrete example',  
                    'Why does this matter?',  
                    'What are common mistakes?',  
                    'Explain it even simpler'  
                  ].map((s) => (  
                    <button  
                      key={s}  
                      onClick={() => setChatInput(s)}  
                      className="text-[12px] px-2.5 py-1 rounded-full bg-[var(--bm-card)] border border-[var(--bm-border)] text-[var(--bm-text-soft)] hover:text-[var(--bm-text)] hover:border-[var(--bm-text)]/30 transition-colors"  
                    >  
                      {s}  
                    </button>  
                  ))}  
                </div>  
              )}  
            </div>  
          </div>  
        )}  
      </div>  
    )}  

    {/* Empty state suggestions */}  
    {!streaming && !hasAnyContent && (  
      <div className="mt-10 fade-in">  
        <div className="text-xs uppercase tracking-wider text-[var(--bm-text-faint)] mb-3 text-center">  
          Try one of these  
        </div>  
        <div className="flex flex-wrap justify-center gap-2">  
          {[  
            'How does compound interest work?',  
            'Explain quantum entanglement',  
            'What is a transformer model?',  
            'How to build a habit that sticks',  
            'Why do we dream?'  
          ].map((s) => (  
            <button  
              key={s}  
              onClick={() => {  
                setTopic(s);  
                handleExplain(s, mode);  
              }}  
              className="text-sm px-3 py-1.5 rounded-full bg-[var(--bm-card)] border border-[var(--bm-border)] text-[var(--bm-text)] hover:border-[var(--bm-text)]/30 transition-colors"  
            >  
              {s}  
            </button>  
          ))}  
        </div>  
      </div>  
    )}  
  </main>  

  {/* History sidebar */}  
  {sidebarOpen && (  
    <div className="fixed inset-0 z-30">  
      <div className="absolute inset-0 bg-[var(--bm-overlay)]" onClick={() => setSidebarOpen(false)} />  
      <aside className="absolute right-0 top-0 h-full w-full sm:w-[380px] bg-[var(--bm-card)] border-l border-[var(--bm-border)] shadow-xl flex flex-col">  
        <div className="flex items-center justify-between px-5 h-14 border-b border-[var(--bm-border)]">  
          <div className="flex items-center gap-2">  
            <History className="h-4 w-4" />  
            <span className="font-semibold text-[15px]">History</span>  
            <span className="text-xs text-[var(--bm-text-soft)]">({history.length})</span>  
          </div>  
          <div className="flex items-center gap-2">  
            {history.length > 0 && (  
              <button  
                onClick={clearHistory}  
                className="text-xs text-[var(--bm-text-soft)] hover:text-[var(--bm-text)]"  
              >  
                Clear all  
              </button>  
            )}  
            <button  
              onClick={() => setSidebarOpen(false)}  
              className="h-8 w-8 inline-flex items-center justify-center rounded-lg hover:bg-[var(--bm-subtle)]"  
              aria-label="Close"  
            >  
              <X className="h-4 w-4" />  
            </button>  
          </div>  
        </div>  

        {/* Sync code panel */}  
        <div className="px-4 py-3 border-b border-[var(--bm-border)] bg-[var(--bm-subtle)]/40">  
          <button  
            onClick={() => setShowSyncCode((v) => !v)}  
            className="w-full flex items-center justify-between text-left"  
          >  
            <div className="flex items-center gap-2">  
              <Sparkles className="h-3.5 w-3.5 text-[var(--bm-accent)]" />  
              <span className="text-[12px] font-medium text-[var(--bm-text)]">  
                Sync across devices  
              </span>  
            </div>  
            <span className="text-[11px] text-[var(--bm-text-soft)]">  
              {showSyncCode ? 'Hide' : 'Show'}  
            </span>  
          </button>  
          {showSyncCode && (  
            <div className="mt-3 space-y-3">  
              <div>  
                <div className="text-[11px] uppercase tracking-wider text-[var(--bm-text-soft)] mb-1">  
                  Your sync code  
                </div>  
                <div className="flex items-center gap-2">  
                  <code className="flex-1 text-[11px] font-mono break-all bg-[var(--bm-card)] border border-[var(--bm-border)] rounded-md px-2 py-1.5 text-[var(--bm-text)]">  
                    {userId || '…'}  
                  </code>  
                  <button  
                    onClick={() => {  
                      if (userId) {  
                        navigator.clipboard.writeText(userId);  
                        toast.success('Sync code copied');  
                      }  
                    }}  
                    className="h-8 w-8 inline-flex items-center justify-center rounded-md border border-[var(--bm-border)] bg-[var(--bm-card)] hover:border-[var(--bm-text)]/30"  
                    aria-label="Copy sync code"  
                  >  
                    <Copy className="h-3.5 w-3.5" />  
                  </button>  
                </div>  
                <div className="text-[11px] text-[var(--bm-text-soft)] mt-1.5">  
                  Copy this on one device, paste it on another to share your history.  
                </div>  
              </div>  
              <div>  
                <div className="text-[11px] uppercase tracking-wider text-[var(--bm-text-soft)] mb-1">  
                  Apply a sync code  
                </div>  
                <div className="flex items-center gap-2">  
                  <input  
                    value={syncCodeInput}  
                    onChange={(e) => setSyncCodeInput(e.target.value)}  
                    placeholder="paste sync code…"  
                    className="flex-1 text-[12px] font-mono bg-[var(--bm-card)] border border-[var(--bm-border)] rounded-md px-2 py-1.5 text-[var(--bm-text)] focus:outline-none focus:ring-1 focus:ring-[var(--bm-accent)]"  
                  />  
                  <button  
                    onClick={applySyncCode}  
                    className="text-[12px] font-medium px-3 py-1.5 rounded-md bg-[var(--bm-accent)] text-white hover:bg-[var(--bm-accent-hover)] transition-colors"  
                  >  
                    Apply  
                  </button>  
                </div>  
              </div>  
            </div>  
          )}  
        </div>  
        <div className="flex-1 overflow-y-auto p-3">  
          {history.length === 0 ? (  
            <div className="text-center text-sm text-[var(--bm-text-soft)] py-20">  
              No history yet.  
              <br />  
              Your past explanations will appear here.  
            </div>  
          ) : (  
            <ul className="space-y-2">  
              {history.map((h) => (  
                <li  
                  key={h.id}  
                  className={cn(  
                    'group rounded-xl border bg-[var(--bm-card)] transition-colors',  
                    h.favorite  
                      ? 'border-[var(--bm-accent-soft-border)] bg-[var(--bm-accent-soft)]/30'  
                      : 'border-[var(--bm-border)] hover:border-[var(--bm-text)]/30'  
                  )}  
                >  
                  <div className="flex items-start gap-2 p-3">  
                    <button onClick={() => loadFromHistory(h)} className="flex-1 text-left">  
                      <div className="flex items-center gap-1.5 text-[14px] font-medium text-[var(--bm-text)]">  
                        {h.favorite && (  
                          <Star className="h-3.5 w-3.5 text-[var(--bm-accent)] fill-[var(--bm-accent)] shrink-0" />  
                        )}  
                        <span className="line-clamp-2 flex-1">{h.topic}</span>  
                      </div>  
                      <div className="mt-1 text-[11px] text-[var(--bm-text-soft)]">  
                        {new Date(h.created_at).toLocaleString()} · {h.mode} mode  
                      </div>  
                    </button>  
                    <div className="flex flex-col gap-1 shrink-0">  
                      <button  
                        onClick={(e) => {  
                          e.stopPropagation();  
                          toggleFavorite(h.id);  
                        }}  
                        className={cn(  
                          'h-7 w-7 inline-flex items-center justify-center rounded-md transition-colors',  
                          h.favorite  
                            ? 'text-[var(--bm-accent)] opacity-100'  
                            : 'text-[var(--bm-text-faint)] hover:text-[var(--bm-accent)] hover:bg-[var(--bm-subtle)] opacity-60 group-hover:opacity-100'  
                        )}  
                        aria-label={h.favorite ? 'Unfavorite' : 'Favorite'}  
                        title={h.favorite ? 'Remove from favorites' : 'Add to favorites'}  
                      >  
                        <Star  
                          className={cn(  
                            'h-3.5 w-3.5',  
                            h.favorite && 'fill-[var(--bm-accent)]'  
                          )}  
                        />  
                      </button>  
                      <button  
                        onClick={(e) => {  
                          e.stopPropagation();  
                          deleteFromHistory(h.id);  
                        }}  
                        className="h-7 w-7 inline-flex items-center justify-center rounded-md text-[var(--bm-text-faint)] hover:text-[var(--bm-text)] hover:bg-[var(--bm-subtle)] opacity-0 group-hover:opacity-100 transition-opacity"  
                        aria-label="Delete"  
                      >  
                        <Trash2 className="h-3.5 w-3.5" />  
                      </button>  
                    </div>  
                  </div>  
                </li>  
              ))}  
            </ul>  
          )}  
        </div>  
      </aside>  
    </div>  
  )}  

  {/* Footer */}  
  <footer className="border-t border-[var(--bm-border)] bg-[var(--bm-card)]">  
    <div className="mx-auto max-w-5xl px-5 sm:px-8 h-14 flex items-center justify-between text-xs text-[var(--bm-text-soft)]">  
      <span>BrainMate · Understand anything. Take action.</span>  
      <span>Powered by AI · streaming</span>  
    </div>  
  </footer>  
</div>

);
}

export default App;
